### ISSUE TITLE
Consider whether minions with no archery skill should pick up bows

### ISSUE THREAD

**Issue by miki151** [miki151/keeperrl#1018]
Or even not being able to use them at all

**Comment by red-kangaroo** [comment]
They should not pick up and use bows unless specifically given bows (and locked) by the player, and then they should try to use the bows, IMHO. Right now, melee minions are way too eager to snatch bows before my harpies can equip them. However, maybe a new, weaker ranged unit could be introduced, like orc archers, to make more minions capable of using bows efficiently?

**Comment by Hunteil** [comment]
make it an upgrade ability from the research. They don't get the ability unless it's researched.
If the unit is not a minion of a keeper, then they get the ability naturally.

And I agree, I couldn't recruit harpies until I locked the room with the bow in it.

**Comment by RighteousSinner** [comment]
units without archery skill can no longer can use bows.
