### ISSUE TITLE
Add a room where minions can go if they have nothing else to do

### ISSUE THREAD

**Issue by miki151** [miki151/keeperrl#1019]
Just to keep them from wandering into the pigsty, etc.

**Comment by Hunteil** [comment]
My game, my orcs clogged up the crafting rooms and just stood there w/no work. Very annoying, but I think my minions traveled through them okay. Some units just wandered in my equipment room or pigsty.

Maybe a Leisure room or Guard room or Game room or let them do rituals.

Guard room is a room where any minion can go to to walk around in off times. I would give it settings that can be changed by Keeper. i.e. Max number of units = half the number of tiles but keeper can change value to prevent clogging, can select what units are allowed to perform duties.

Leisure room is a room where any minion can go sit down, slack off, watch the crystal ball (tv), read a good romance novel. Would increase moral, decrease level slowly, increase copulation chance? Maybe it needs to be used in tandem with beds for it to work with succubus?

Game room is a room where any minion can go and play poker, dance, throw heads & limbs into hoops... would increase moral. Give purpose to chopping off limbs, chance of poison gas. Level up throwing skill? poker wouldn't use gold I'd expect.

These are just ideas. Would love to see more rooms though.
I'm thinking Game and Leisure would require special programing though for the furniture spawning.

**Comment by RighteousSinner** [comment]
fixed with leisure zones
