### ISSUE TITLE
SDL2/SDL_image.h: No such file or directory

### ISSUE THREAD

**Issue by diamond-lizard** [miki151/keeperrl#1038]
When I `make OPT=true RELEASE=true` on Gentoo Linux amd64 I get an error:  `SDL2/SDL_image.h: No such file or directory`

The full log of the build is [here](https://gist.github.com/diamond-lizard/f67285143480f94649653b9f93422ad2).

I am using libsdl2 version 2.0.4, and the contents of `/usr/include/SDL2` can be seen [here](https://gist.github.com/diamond-lizard/3a58e333a0401b42635b76b911348b4e).  As you can see, there is no `SDL_image.h` in that directory.

**Comment by miki151** [comment]
You need libsdl2-image-dev installed, which is a separate package from
libsdl2.

**Comment by diamond-lizard** [comment]
It doesn't look like there's such a package on Gentoo.  The only SDL2-related package is `media-libs/libsdl2`, which I already have installed.  There is a `media-libs/sdl-image`, but the only available version of it is 1.2.12-r1, which I already have installed anyway.

(PS: Just fyi, there are no -dev packages on Gentoo.  Virtually every package is compiled from source, so effectively they're all -dev's.)

**Comment by miki151** [comment]
In this case you are left with compiling by hand.
https://www.libsdl.org/projects/SDL_image/
