### ISSUE TITLE
Pig gases hurts Keeper and game requests

### ISSUE THREAD

**Issue by Hunteil** [miki151/keeperrl#1040]
I don't know if this should be tied in with the other Pig request for imps to clean them. So making separate just in case.

Anyways, finally picked up the game after a yr of not playing. Next changes are cool btw. Anyways, after hours of playing with the Keeper and messing with monsters, digging etc etc etc. I get a prompt, my keeper is under attack. Do you want to control him? So I press okay and freak out... only to find the pig gases are hurting him and nothings wrong... a week of me playing the game goes by. I get this prompt every hour it seems. It's very annoying and the keeper just runs back to bed every time and there's nothing to worry about unless he gets stuck in the room some how.

Solution: Make the keeper immune to pig attacks and/or pig gases only. He can still be affected by normal gases. But the pig gases can be ignored. Or if there's some other way to fix it... do that like imp clean up of pigs. Or add a fan to blow out gases.

**Comment by miki151** [comment]
Pig corpses won't emit gas, that should fix the issue.
