### ISSUE TITLE
Unit boxed in on top of blocking tiles

### ISSUE THREAD

**Issue by Hunteil** [miki151/keeperrl#1043]
So after I realized my crafting room tiles blocked units from entering them. I decided to build the tiles around the edge of the room instead. I had a Orc in the corner of the room and built a crafting table under him, to the top of him and to the right of him. There was a wall to the bottom and left of him. After the Imps built. I couldn't move him out of the corner anymore using manual controls. He was stuck.

My solution was to travel with him to different villain area then back again which moved him to edge of map and he was free again.

Side note: Did this again with another Orc, same room. He was on top of craft table, open tile above. Manually moved him and he was fine.

**Comment by miki151** [comment]
Dulicate of #977
