### ISSUE TITLE
Weight of items. Please explain

### ISSUE THREAD

**Issue by Hunteil** [miki151/keeperrl#1044]
Sorry, Pressed enter too soon.

Basically, I knew things had weight. But didn't know how to tell what the weight of things had until I had a huge fight and dead bodies were everywhere among the forest. This got complicated sifting through the loot. So I picked up bodies and moved them into one pile to start organising what piles of blood and flesh I went through. This is when I realized Orcs and Ogres were REALLY heavy. (makes sense.)

I saw on the side of the entry (900s)

I guess this is the weight... whereas inspect bodies were each (1s)

What does "s" mean? This gonna be changed into lb or kg?

**Comment by red-kangaroo** [comment]
It's "s" for "stones", I presume, an old unit of weight.

BTW, why should it be changed?

**Comment by Hunteil** [comment]
Well it doesn't need to be changed I guess. But if you look at your average player coming into the game. They may also be just as confused.

If you want to keep that unit of measurement. Then I'd say make sure it's in the keeperpedia in game to explain it. I played the heck out of this game for 3 months and never figured it out until this most recent play through. (thanks btw) I thought it stood for seconds to pick up or seconds to do something. I had no idea lol.

**Comment by miki151** [comment]
I copied the 's' unit from other games, but I can see how you can confuse it with seconds. The problem with lb or kg is that 1s is 0.1kg, so you'll get a lot of decimals.

If I add your total carrying capacity above the inventory list, that should also explain the units, I think.

**Comment by Hunteil** [comment]
^I can deal with that. :-)

**Comment by miki151** [comment]
Cool, it will be out with the next update. Thanks :)
