### ISSUE TITLE
Add wizards to knight castle

### ISSUE THREAD

**Issue by red-kangaroo** [miki151/keeperrl#1051]
Knights are a powerful end-game enemy, but they would benefit from a spellcaster support, both when you assault their castle and when they come to siege your dungeon. Wizards should know rather high-end spells, but only use robes and staffs, making them easy to kill if you can catch them in melee combat. They could work well as a support unit, healing and buffing knights, plus debuffing your minions.

As a bonus feature for us who like adventurer mode quite a bit, adventurers might be able to chat with wizards in the castle and pay them very hefty sums of gold to learn spells.

**Comment by Hunteil** [comment]
There's so many moving gears on this one.

1. I read that Knights are really hard in the 1st place to defend against. (I haven't gotten to see the new change on Knights yet, need to buy new part for PC) So I can't weigh in on this one yet.

2. They would be a good castle defender for sure.

3. Buying spells is nice, but for adventure mode, you get scrolls for this purpose it seems. So maybe buy scrolls from them instead and/or perform spells for you.

4. Maybe when you find a research book, you can sell them to the wizards or something?

4.

**Comment by RighteousSinner** [comment]
completed. current priest unit.
