### ISSUE TITLE
Adventurers need a way to learn archery and magic

### ISSUE THREAD

**Issue by miki151** [miki151/keeperrl#1152]

**Comment by SoftMonster** [comment]
What would be neat is if players could do the training task as a command like sleeping on a bed and would carry on until completed or interrupted just like sleeping on beds. The option would appear when next to a training dummy - like the sleep on bed option appears when you are on a bed tile. Just one way of doing it but feels like a good option.

**Comment by SoftMonster** [comment]
Another option: pay allied tribe leaders gold to train levels in archer, sorcery, combat.

**Comment by SoftMonster** [comment]
Another option. Buy skill potions from shopkeeper to train levels.

**Comment by RighteousSinner** [comment]
fixed via coded skill trees
