### ISSUE TITLE
Consider whether ants/ada golems should defend their resources and not full on attack

### ISSUE THREAD

**Issue by miki151** [miki151/keeperrl#1166]

**Comment by SoftMonster** [comment]
Ants and ada golems could get reinforcements if the leader survives.

**Comment by SoftMonster** [comment]
2) Their leader could get slightly higher stats and a modified description.

**Comment by SoftMonster** [comment]
They could have random attack triggers, so sometimes they could go for your keeper, other times they could kill a few of your troops and then return. Other times they could just wait to be attacked first and then counter attack if provoked.

**Comment by SoftMonster** [comment]
They could just be the same as now, but a bit more defensive.

**Comment by SoftMonster** [comment]
They could literally defend the resources by going for your imps and prisoners.
