### ISSUE TITLE
Use special sprites for equipment with prefixes

### ISSUE THREAD

**Issue by miki151** [miki151/keeperrl#1182]

**Comment by SoftMonster** [comment]
Could make them special by adding an aura (like the ego minions have). Other options are to have an extra view ID for each item to display when it is an ego. The best/most complicated option might be to have the ego item code identify a suitable sprite based on the type of item it is and the type of ego it is.

**Comment by SoftMonster** [comment]
Ego weapons could also get a +3 damage buff. Swords of fire would be about +11 normal damage.

**Comment by miki151** [comment]
I added an "aura" to special items. Nice idea.
