### ISSUE TITLE
Make vampire lord source of darkness intrinsically

### ISSUE THREAD

**Issue by miki151** [miki151/keeperrl#1185]
He burns to death when enslaved

**Comment by SoftMonster** [comment]
Also possible to enslave zombies that will die outside in the sunlight. Nobody will care about that one, but going forward, perhaps undead ought to be recruited directly into your prisoner, rather than having to travel outside to get there?

**Comment by SoftMonster** [comment]
If the vampire lord goes back to intrinsic darkness, he could still carry the permanent darkness scroll with him.

**Comment by Draethorian** [comment]
or you just have to beat a dungeon to get the scroll?
