### ISSUE TITLE
Make zombies less useless

### ISSUE THREAD

**Issue by miki151** [miki151/keeperrl#1187]
Make them explode on death or something

**Comment by SoftMonster** [comment]
Poison touch intrinsic attack (when not wielding)?

**Comment by SoftMonster** [comment]
Zombies could spread disease with their intrinsic attack (a new effect that gives you lower damage and defence). Disease could have the added fun of spreading to adjacent creatures but it would wear off on a timer like other lasting effects. Undead would be immune. When the disease wears off, you could develop an immunity and get a permanent disease resistance effect. similar to what the undead would have from the beginning.

**Comment by SoftMonster** [comment]
Another option - Zombies could release poison gas instead of corpses.
