### ISSUE TITLE
Allow claiming tiles outside of the dungeon (?)

### ISSUE THREAD

**Issue by miki151** [miki151/keeperrl#1189]
- Poor mans buildings?
- If not, allow building moats outside somehow

**Comment by SoftMonster** [comment]
Actually there is a bug here. If you capture a village hut from a human tribe on your dungeon map sector, surprisingly you can claim the tiles inside the hut and build a floor there etc. I uploaded a save file showing this.

**Comment by SoftMonster** [comment]
What you can't do is claim grass or hills - that is what I think the players actually want to do. You can claim floor tiles (little known fact).
