### ISSUE TITLE
Prisoners not being poison resistant may cause issues when carrying corpses.

### ISSUE THREAD

**Issue by miki151** [miki151/keeperrl#1193]

**Comment by SoftMonster** [comment]
Corpses could only release poison gas when they are on the floor.

**Comment by SoftMonster** [comment]
or 2) Corpse poison could only poison creatures that are walking on enemy tiles. So defenders would be immune.

**Comment by SoftMonster** [comment]
or 3) Corpses could stop releasing poison (although I am rather fond of that).

**Comment by SoftMonster** [comment]
or 4) Prisoners could have a hidden poison immunity
