### ISSUE TITLE
Potion of Limb regrowth

### ISSUE THREAD

**Issue by Draethorian** [miki151/keeperrl#1196]
Because I managed to captivate a vampire lord without a head and a very dear orc shaman of mine lost a leg in a fight.

**Comment by miki151** [comment]
Try killing the lizardmen chief :)

**Comment by Draethorian** [comment]
Then what about being able to brew it myself?

Michal Brzozowski <notifications@github.com> schrieb am Mi., 25. Juli 2018,
11:14:

**Comment by Draethorian** [comment]
Alright. Thanks for the info ;-)
