### ISSUE TITLE
Tentacle unkillable...

### ISSUE THREAD

**Issue by ghost** [miki151/keeperrl#1198]
![capture](https://user-images.githubusercontent.com/19950085/43221616-a0b36786-904d-11e8-9204-cb5ce0d197e6.PNG)

lol wtf^^
![capture](https://user-images.githubusercontent.com/19950085/43221846-640a7c60-904e-11e8-80f7-3869b8c710f4.PNG)

alright i figured yo have to have att least 2 tiles broad tunnels in order to chop thet tentacle back to the kraken. (and killing one piece of the tentacle kills all the following)

**Comment by miki151** [comment]
Do you mean that it spawns too fast for you to kill it and then move into its tile to kill the next one?

**Comment by Draethorian** [comment]
Yep exactly^^

Michal Brzozowski <notifications@github.com> schrieb am Do., 26. Juli 2018,
09:09:
