### ISSUE TITLE
New immigration modding requests

### ISSUE THREAD

**Issue by SoftMonster** [miki151/keeperrl#1312]
1) I'd like to have support for NOT logic in the immigration requirements.

One application of this is to buff immigrants when you get technologies. You could have a tech: Elite orcs. Elite orcs would be tougher and appear when you get the tech. The problem is that I can't turn off the "not elite orcs" when I get the "Elite orcs" technology. I can't buff all the immigrants.

So I want to turn off the not elite orcs when I get "Elite orcs" tech. Same thing would be useful to turn off certain immigrants when you get a throne or reach a certain turn number. Same reason.

2)  A special trait that overwrites the name like turns "orc" into "Elite orc"

3) Able to delete all carried items and add your own items to the immigrants. Immigrants could bring different items into your dungeon when they join.

Thanks for considering my requests :)

**Comment by miki151** [comment]
1. I've Added NegateRequirement, ex. "NegateRequirement TechId "Elite orcs"".

2. Since you can add new creatures in a mod, just add a modified elite orc

3. Immigrants are stripped of equipment by default, but I've added a stripEquipment flag, set it to false and the immigrant will come with his original equipment. You can modify it in creature_inventory.txt.

**Comment by miki151** [comment]
SoftMonster could you please let the original author of the request know? I think it was someone on discord? Thx.

**Comment by SoftMonster** [comment]
Thanks for this Michal, looks good! I have put a post on discord linking to this item. I know people have been asking for this and it will be of interest to the community.

**Comment by SoftMonster** [comment]
Upgrading minions with technology was first requested on steam here:

https://steamcommunity.com/app/329970/discussions/5/1743352529782003256/

Posted an update
