### ISSUE TITLE
Weapon runes

### ISSUE THREAD

**Issue by miki151** [miki151/keeperrl#1315]
When a rune is in storage then it's consumed for production of an artifact. Optionally allow choosing a specific rune to craft an artifact

Allow building equipment from other found items like dragon hide, teeth, etc

Dragon hide: resistances
Dragon tooth: attacks
Dragon eye: potion?
Cyclops, minotaur: extra defense
Hydra tongue?
Spider silk: ?
Unicorn horn: ?
Ant queen: acid?

**Comment by GameDoungen** [comment]
This is in the game.
