### ISSUE TITLE
More minions for white knights

### ISSUE THREAD

**Issue by SoftMonster** [miki151/keeperrl#1318]
White knights need a greater variety of minions, especially more powerful ones later on in the game. Compare with warlocks, that have legendary beasts, legendary humanoids, vampires, werewolves and doppelgangers - the warlocks are more fun to play at the moment.

This can be a configuration change.

**Comment by keepermanj** [comment]
Possible solution to issue:

https://github.com/miki151/keeperrl/pull/1325
