### ISSUE TITLE
Legendary beasts need improved stats

### ISSUE THREAD

**Issue by SoftMonster** [miki151/keeperrl#1320]
This is a configuration change.

From Discord:

Prophet Devengel
Are legendary beasts worth it ?

Soft MonsterYesterday at 8:16 PM
@Prophet Devengel To be honest, I find legendary beasts a bit under powered at the moment. They tend to have similar stats to lengendary humanoids but cannot train skills and do not have enough interesting intrinsic attacks to compensate for not using weapons. Just my opinion.

Prophet DevengelYesterday at 8:19 PM
don't worry
your opinion is completely valid
i've got this legendary beast that looks like a slime, he got one shotted by a spirit
i understand that he is weak to magic attacks, but one SHOT!, and HE COSTED 100 golds
and gold isn't easy to get, and there isn't infinite source of it either.

**Comment by keepermanj** [comment]
I can't see legendary beasts in the configs actually.  I think they might be a special case. They maybe need +10 DAMAGE and +10 DEFENSE to make up for the fact that they can't train 10 levels and can never research any spells. 100 gold is a fair price for that.

**Comment by miki151** [comment]
They're going to be overhauled in a future update, closing for now
