### ISSUE TITLE
Configure a layer of bedrock in zlevels.txt

### ISSUE THREAD

**Issue by SoftMonster** [miki151/keeperrl#1321]
Firstly, I'd like to say that it is really, really exciting to have my base many levels deep, on top of a massive rogue-like dungeon.

Most rogue-like games only save the current dungeon level and when you leave that level, the dungeon at that depth is deleted from memory for ever. Keeper needs to save the entire dungeon at all depths and sadly, this means it will run out of memory at some point.

It doesn't really make sense to allow players to dig off the bottom of the world, or crash the game by running it out of memory. I'd love to be able to handle 100 dungeon crawl levels but the dungeons need to have a depth limit, so that they can be persisted in the save file. The dungeon needs to hit a layer of bedrock at some point to stop you digging further down.

Which brings me to this modding request. Would it be possible to configure how deeply the z-levels go in the file "zlevels.txt"? At least this way I can play against a very deep dungeon if I can find some extra RAM.

Also, I would like to change this, so that the deepest levels are random dungeons with worse and worse monsters, instead of filled rock:

  -- This is an filled level that can appear at all depths
  {
    type = FullZLevel {
    }
  }

Perhaps you can explain how this works in some more detail.

Thanks

Soft Monster

**Comment by SoftMonster** [comment]
Hi,

Sorry if this is really a different issue, I decided to put this all together under the same issue. I know this is early days for Alpha 27, so I am hoping to help think this through.

I can't find a way to generate dungeon mazes. I did make some progress, because I found 19 different ENEMEY_ID that work. I tried most of the ENEMY_ID options and I removed the ones that errored. The IDs that might have generated interesting mazes wanted to error. The ones that worked are in my configs shown below. Perhaps this is of interest and perhaps there is a way to get dungeon mazes generated instead of filled levels (which would be REALLY nice :)

# Here come levels for all keeper types
# At every depth the game chooses a random level that's available
# They are generated on the fly when stairs are built so you can edit this file while the game is running.
{
  # This is an filled level that can appear at all depths
{   type = FullZLevel { enemy = ELEMENTALIST_ENTRY  }  minDepth = 1 maxDepth = 1}
{   type = FullZLevel { enemy = ELEMENTALIST  }  minDepth = 2 maxDepth = 2}
{   type = FullZLevel { enemy = RED_DRAGON  }  minDepth = 3 maxDepth = 3}
{   type = FullZLevel { enemy = GREEN_DRAGON  }  minDepth = 4 maxDepth = 4}
{   type = FullZLevel { enemy = MINOTAUR  }  minDepth = 5 maxDepth = 5}
{   type = FullZLevel { enemy = BANDITS  }  minDepth = 6 maxDepth = 6}
{   type = FullZLevel { enemy = NO_AGGRO_BANDITS  }  minDepth = 7 maxDepth = 7}
{   type = FullZLevel { enemy = CYCLOPS  }  minDepth = 8 maxDepth = 8}
{   type = FullZLevel { enemy = SHELOB  }  minDepth = 9 maxDepth = 9}
{   type = FullZLevel { enemy = ANTS_OPEN  }  minDepth = 10 maxDepth = 10}
{   type = FullZLevel { enemy = ANTS_CLOSED  }  minDepth = 11 maxDepth = 11}
{   type = FullZLevel { enemy = ANTS_CLOSED_SMALL  }  minDepth = 12 maxDepth = 12}
{   type = FullZLevel { enemy = DWARF_CAVE  }  minDepth = 13 maxDepth = 13}
{   type = FullZLevel { enemy = ADA_GOLEMS }  minDepth = 14 maxDepth = 14}
{   type = FullZLevel { enemy = KOBOLD_CAVE  }  minDepth = 15 maxDepth = 15}
{   type = FullZLevel { enemy = DARK_ELVES_ENTRY  }  minDepth = 16 maxDepth = 16}
{   type = FullZLevel { enemy = GNOMES_ENTRY  }  minDepth = 17 maxDepth = 17}
{   type = FullZLevel { enemy = OGRE_CAVE  }  minDepth = 18 maxDepth = 18}
{   type = FullZLevel { enemy = HARPY_CAVE  }  minDepth = 19 maxDepth = 19}
}

# Here come levels specific to white keepers
{
  {
    type = FullZLevel {
      enemy = DARK_ELF_CAVE
    }
    minDepth = 200
  }
}

# Here come levels specific to dark keepers
{
  {
    type = FullZLevel {
      enemy = DWARF_CAVE
    }
    minDepth = 200
  }
}

**Comment by SoftMonster** [comment]
Just to be clear, the config above works without erroring but doesn't produce any mazes.

**Comment by miki151** [comment]
It's still work in progress, you're going to be satisfied once it's done:)
