### ISSUE TITLE
Crash in the current git head

### ISSUE THREAD

**Issue by singalen** [miki151/keeperrl#1334]
stack: https://gist.github.com/singalen/d0514bd4214d7661a7fe8781ace35f31
It's not clear what caused it.

**Comment by singalen** [comment]
It would be nice to periodically save progress internally, and restore the game state on the next launch from there if the game crashed. This save doesn't have to be available to the user and would be deleted if the game exits normally.

**Comment by miki151** [comment]
There is autosave, maybe you have it turned off? Thanks for the stack trace, hopefully I can figure out the issue.

**Comment by singalen** [comment]
Autosave and "keep saves" options are on. I couldn't see a `savefile` or anything in the directory.

**Comment by keepermanj** [comment]
Sometimes it can crash before the first autosave

**Comment by miki151** [comment]
Should be fixed now.
