### ISSUE TITLE
Area effects

### ISSUE THREAD

**Issue by miki151** [miki151/keeperrl#1335]
Allow attaching lasting effects to positions via effects or permanently to furniture.

Panic
Slowed
Speed
Attr bonus/debuff
Bleeding
Blindness - last two could span whole levels
X resistance/vuln
Regeneration

**Comment by SoftMonster** [comment]
Would you consider making it work like the poison gas effect, so you can use the area effects in a trap. Also, is cool the way poisoned gas is visible on the map in green.  Cloud of blindness, bleeding etc.

**Comment by keepermanj** [comment]
I'm pretty happy with the new area effects. Not sure if anything else neefs adding really.

**Comment by miki151** [comment]
Well your previous idea is cool, I might implement it some time.

**Comment by GameDoungen** [comment]
In the game
