### ISSUE TITLE
Minion who kills a villain leader should get a special title + some upgrade

### ISSUE THREAD

**Issue by miki151** [miki151/keeperrl#1370]

**Comment by RighteousSinner** [comment]
this could probably be set in the enemies.txt as permanent character buff. Getting one of the abilities of the defeated might be cool too, but that would require "skill scrolls" or some other function that lets you learn abilities.

**Comment by keepermanj** [comment]
Or specified in creatures.txt

SlayerTitle = "the dragon slayer"
TitleEffect = DEF_BONUS

**Comment by GameDoungen** [comment]
You added the name part
