### ISSUE TITLE
Git tag for alpha 27

### ISSUE THREAD

**Issue by akien-mga** [miki151/keeperrl#1380]
Congrats on the alpha 27 release!

Could you add the corresponding git tag? The tag was also omitted for alpha 25 BTW, it might be interesting to add it for history's sake.

Thanks!

**Comment by miki151** [comment]
Sure thing, thanks for reminding me. I don't remember alpha 25 release point anymore, I think history will do fine without it :)

**Comment by akien-mga** [comment]
Thanks :)
