### ISSUE TITLE
Consider making it possible to control teams separately in control mode.

### ISSUE THREAD

**Issue by LichenSymbiont** [miki151/keeperrl#1398]
As you get further into the game, you get too many units, and using full control mode is the only way to not having mage-types sacrifice themselves in a battle. Which is of course very time consuming.

So I propose a method for controlling multiple smaller teams by simple commands, like the usual drag-and-drop to move a team to a position, and then a command to hold position. Just this would allow you to have a team of mages / ranged units, that are kept away from the heat of the battle.

But other commands than hold can be implemented, like heal units within range. So they will hold position, and only move out to heal a nearby unit (within a reasonable area, or configurable).

**Comment by miki151** [comment]
This would be pretty complicated to design and would complicate control mode too much, imo. My aim right now is to improve the AI to the point that you don't need to micromanage it too much. If that doesn't work then I'l think about adding more orders.
