### ISSUE TITLE
alpha25 tag is missing

### ISSUE THREAD

**Issue by jbeich** [miki151/keeperrl#1410]
Was it actually [released](https://keeperrl.com/keeperrl-alpha-25-is-released/)? If so what commit the official binaries corresponded to? I'd like a smaller window when bisecting possible regressions e.g., when updating a [downstream package](https://repology.org/project/keeperrl/versions).

**Comment by miki151** [comment]
Alpha 25 hotfix 1 should be 598a8a0c201e78e12081db44bba81449ba7f3f13. Do you need to actual tag on github?
