### ISSUE TITLE
Items that grant certain abilities when equipped

### ISSUE THREAD

**Issue by miki151** [miki151/keeperrl#1411]
Ex. wand of fireball

**Comment by keepermanj** [comment]
Would be good if you could specify a spell id rather than just an effect. Eg.

Sword "healing 3"

This would allow you to specify sounds, ranges, targetting self, cooldowns etc. rather than just specifying an effect on its own that doesn't do those other things.

**Comment by keepermanj** [comment]
I'm pretty sure you did this in Alpha29

**Comment by keepermanj** [comment]
I'm pretty sure you did this in Alpha29

**Comment by miki151** [comment]
Yup
