### ISSUE TITLE
Minion attacks allies without reason

### ISSUE THREAD

**Issue by ivan-mogilko** [miki151/keeperrl#1416]
Playing Alpha 28 hotifx 1, I was exploring the allied location of Dark Elves with a group of minions when one of them started attacking allied creatures for no apparent reason. He was the only one doing so. At first I thought he has "hates all elves" trait, but this is not mentioned in minion's stats.
So, I guess, either there's bug in stats display or bug in AI (unless I completely missed something ofc).

I have attached a savegame, the minion in question is a Orc Mage called "Ghamog".

[Sieglinde_Spidessosuyig.zip](https://github.com/miki151/keeperrl/files/3365838/Sieglinde_Spidessosuyig.zip)

**Comment by miki151** [comment]
My best explanation is that he was temporarily insane or killed one of the dark elves at the top level by accident (notice there are ruins at the entrance to their cave, which have ghosts that can turn you insane). The fact that he didn't attack anyone on your team would suggest it was an accident, like trying to attack a rat, for example. I've tried to make AI not attack allies at all costs, but there may be bugs there.

After he'd killed an elf, all other elves became hostile towards him, so he was fighting back, basically.

I can't do anything more without more info, so I'll close this, but let me know if you notice it happening again or if you have any other issues.
