### ISSUE TITLE
Suggestion to let player close message window with Enter

### ISSUE THREAD

**Issue by ivan-mogilko** [miki151/keeperrl#1422]
Most messages I found in game were referring to enemy faction being destroyed. They usually require to click on "Dismiss" button, which is ok when you are playing a Keeper in strategy mode, but when you are playing Adventure mode you have to switch from keyboard to mouse to close these, and that becomes annoying.

**Comment by ivan-mogilko** [comment]
I need to elaborate, I know that you can Dismiss message windows with Esc key, but it will be nice to have it also closed with Enter if there are no other options.

**Comment by miki151** [comment]
I've made the change, thanks for the suggestion.
