### ISSUE TITLE
Consider making bows have an adjustable range stat

### ISSUE THREAD

**Issue by RighteousSinner** [miki151/keeperrl#1437]
This would make bows more interesting since you could then theoretically make bows that have limited range but high damage or vice versa.

**Comment by keepermanj** [comment]
Bows have a range that is always equal to the damage stat. The elven bow has a range of 15. The short bows have a range of 9-11.

**Comment by miki151** [comment]
I'm pretty sure range is independent from the damage stat and you can change it in items.txt.
