### ISSUE TITLE
Make a moddable "usageEffect" in furniture.txt

### ISSUE THREAD

**Issue by SoftMonster** [miki151/keeperrl#1487]
Make moddable usageEffect in furniture.txt
eg.
  "BLOOD_FOUNTAIN"
  {
    name = "blood fountain"
    viewId = { "blood_fountain" }
    usageType = { "Drink" UsageEffect }
    usageEffect = RegrowBodyPart
    usageCooldown = 1500
  }

**Comment by SoftMonster** [comment]
Another way to implement this could be:

"SURGERY"
{
name = "surgery"
viewId = { "surgery" }
usageType = usageEffect "Replace Limb" RegrowBodyPart 1500
}

**Comment by SoftMonster** [comment]
When you go to the surgery, the option "Replace Limbs" pops up where you would normally see "Drink" or "Open" or some other verb.

**Comment by miki151** [comment]
Done, see for example https://github.com/miki151/keeperrl/commit/37856f5f95c33fdc88a6fe88ec7b2d1d31e2800c
