### ISSUE TITLE
(alpha 29) (windows 10) compilation problem with steam

### ISSUE THREAD

**Issue by myhellone** [miki151/keeperrl#1495]
I can't compile game alpha29
I use this instrucion https://keeperrl.com/compiling-keeperrl-on-windows/ 
I found info on github to add RELEASE=true 

$ make -f Makefile-win -j4 DEBUG=true OPT=true RELEASE=true
Using built-in specs.
COLLECT_GCC=C:\msys64\mingw32\bin\g++.exe
bash ./gen_version.sh
bash ./gen_version.sh
g++ -MMD -Wall -std=c++1y -Wno-sign-compare -Wno-unused-variable -Wno-strict-aliasing -Wl,--stack,16000000 -I. -I./extern -Winvalid-pch -DWINDOWS -g -fno-omit-frame-pointer -DRELEASE -O2  -c window_view.cpp -o obj/window_view.o
g++ -MMD -Wall -std=c++1y -Wno-sign-compare -Wno-unused-variable -Wno-strict-aliasing -Wl,--stack,16000000 -I. -I./extern -Winvalid-pch -DWINDOWS -g -fno-omit-frame-pointer -DRELEASE -O2  -c main.cpp -o obj/main.o
g++ -MMD -Wall -std=c++1y -Wno-sign-compare -Wno-unused-variable -Wno-strict-aliasing -Wl,--stack,16000000 -I. -I./extern -Winvalid-pch -DWINDOWS -g -fno-omit-frame-pointer -DRELEASE -O2  -c game.cpp -o obj/game.o
g++ -MMD -Wall -std=c++1y -Wno-sign-compare -Wno-unused-variable -Wno-strict-aliasing -Wl,--stack,16000000 -I. -I./extern -Winvalid-pch -DWINDOWS -g -fno-omit-frame-pointer -DRELEASE -O2  -c file_sharing.cpp -o obj/file_sharing.o
file_sharing.cpp: In function 'std::experimental::optional<FileSharing::SiteInfo> parseSite(const vector<std::__cxx11::basic_string<char> >&)':
file_sharing.cpp:309:20: warning: catching polymorphic type 'struct cereal::Exception' by value [-Wcatch-value=]
  309 |   } catch (cereal::Exception) {
      |                    ^~~~~~~~~
file_sharing.cpp: At global scope:
file_sharing.cpp:382:3: error: 'steam' does not name a type
  382 |   steam::ItemInfo info;
      |   ^~~~~
file_sharing.cpp: In member function 'std::experimental::optional<vector<ModInfo> > FileSharing::getSteamMods()':
file_sharing.cpp:482:27: error: 'struct SteamItemInfo' has no member named 'info'
  482 |     auto& info = infos[n].info;
      |                           ^~~~
file_sharing.cpp: In member function 'std::experimental::optional<vector<FileSharing::SiteInfo> > FileSharing::getSteamSites()':
file_sharing.cpp:508:27: error: 'struct SteamItemInfo' has no member named 'info'
  508 |     auto& info = infos[n].info;
      |                           ^~~~
file_sharing.cpp: At global scope:
file_sharing.cpp:623:15: warning: 'std::string serializeInfo(const string&, const SavedGameInfo&)' defined but not used [-Wunused-function]
  623 | static string serializeInfo(const string& fileName, const SavedGameInfo& savedInfo) {
      |               ^~~~~~~~~~~~~
file_sharing.cpp:365:15: warning: 'std::string firstLines(std::string, int)' defined but not used [-Wunused-function]
  365 | static string firstLines(string text, int max_lines = 3) {
      |               ^~~~~~~~~~
make[1]: *** [Makefile-win:107: obj/file_sharing.o] Błąd 1
make[1]: *** Oczekiwanie na niezakończone zadania....
window_view.cpp: In member function 'Rectangle WindowView::getMapGuiBounds() const':
window_view.cpp:84:1: warning: control reaches end of non-void function [-Wreturn-type]
   84 | }
      | ^
window_view.cpp: In member function 'Vec2 WindowView::getOverlayPosition(GuiBuilder::OverlayInfo::Alignment, int, int, int, int)':
window_view.cpp:505:1: warning: control reaches end of non-void function [-Wreturn-type]
  505 | }
      | ^
window_view.cpp: In lambda function:
window_view.cpp:809:13: warning: control reaches end of non-void function [-Wreturn-type]
  809 |             }();
      |             ^
window_view.cpp: In member function 'virtual double WindowView::getGameSpeed()':
window_view.cpp:1477:1: warning: control reaches end of non-void function [-Wreturn-type]
 1477 | }
      | ^
make: *** [Makefile-win:94: all] Błąd 2

**Comment by rardiol** [comment]
There's a bug on alpha29 for building without steamworks. Try the stable branch or alpha29hotfix1: https://github.com/miki151/keeperrl/tree/stable

You can switch by running "git checkout stable" inside the source directory.

**Comment by miki151** [comment]
This should be fixed now, I think.
