### ISSUE TITLE
Doppleganger can aborb hydra and spiders in mods

### ISSUE THREAD

**Issue by SoftMonster** [miki151/keeperrl#1508]
Modders could ban hydra and spiders from being summoned in the first place. I would prefer it if there could be an UNABSORBABLE lasting effect that can be placed on creatures. Then, dopplegangers won't be able to grow 8 legs, 6 heads and wear endless boots and helmets.

**Comment by miki151** [comment]
Why not? I think it's pretty cool :)

**Comment by SoftMonster** [comment]
It is cool.but OP. All those helmets and boots

**Comment by SoftMonster** [comment]
You know what, it is pretty cool :) dopples have been nerfed a lot already. Maybe it is ok.

**Comment by SoftMonster** [comment]
I'm going to close the issue because I don't want to clutter up the issues queue with things that are not real issues.
