### ISSUE TITLE
PermanentSummon effect needed for artifact summon items

### ISSUE THREAD

**Issue by SoftMonster** [miki151/keeperrl#1509]
A permanent summon effect (one that doesn't add the SUMMONED lasting effect). It would allow artifact scrolls and other artefact items to summon a one-off permanent ally.

**Comment by SoftMonster** [comment]
Will be nice to use in mods.

**Comment by miki151** [comment]
https://github.com/miki151/keeperrl/commit/b00e2eb66f107c2c181ae0d4687d8076757b9667

A ttl field is required now, you can change it to "none" for a permanent summon.
