### ISSUE TITLE
Ability to set different wilderness items for different villains

### ISSUE THREAD

**Issue by SoftMonster** [miki151/keeperrl#1512]
Currently, all villains use "wildernessItems" in item_lists.txt, which tend to be mushrooms.

I would like to dot around herbs instead of mushrooms for the driad lesser villains etc. Will give flavor to the different maps.

**Comment by miki151** [comment]
Good idea

**Comment by miki151** [comment]
I've made biomes moddable so you can add a new inheriting biome with you items redefined. https://github.com/miki151/keeperrl/blob/master/data_free/game_config/biomes.txt
