### ISSUE TITLE
Digging a staircase down should leave the imp at the bottom of the stairs

### ISSUE THREAD

**Issue by SoftMonster** [miki151/keeperrl#1518]
Digging down a z-level should leave you at the bottom for gameplay reasons. Otherwise, you have to take a creature down the stairs manually to explore the level before you can dig out the new level.

Other than that, digging down would realistically leave you at the bottom not the top.

I think this would be a really good idea.

**Comment by miki151** [comment]
The issue with not being able to dig is already fixed in A30, so this won't really do anything
