### ISSUE TITLE
Make tribal loyalties moddable

### ISSUE THREAD

**Issue by SoftMonster** [miki151/keeperrl#1544]
I documented the vanilla loyalties on the wiki.

http://keeperrl.com/wiki/index.php?title=Category:Tribes#Tribal_loyalties

These could be moddable.

**Comment by miki151** [comment]
Won't work due to mixing mods and adding modded retired dungeons.

**Comment by SoftMonster** [comment]
OK. Will close. No point in leaving it open if it isn't workable.
