### ISSUE TITLE
"Break" effect from Chain, FirstSuccessful, Area, etc.

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [miki151/keeperrl#1573]
An effect that causes those loops to stop.

**Comment by miki151** [comment]
Could you give me an example usage?

**Comment by LudwigVonChesterfield** [comment]
Killing only one creature in an area.

Or executing a chain only if certain criteria are met and quitting otherwise
(make BREAK effect return "true" on applies):

```
Area 30 {
  Filter ENEMY ChainFirstResult {
    BREAK
    Suicide DIE
  }
}
```

**Comment by LudwigVonChesterfield** [comment]
(perhaps if coupled with a "NOT" effect would be very good)

**Comment by LudwigVonChesterfield** [comment]
currently there is no way of implementing a negative lookahead kind of thing, where you check for something, and if it's "true"-sy, you don't do an action

**Comment by miki151** [comment]
I don't think this is possible to implement, especially from a few levels deep. You want a programming language basically :)
