### ISSUE TITLE
Whitelist/blacklist automaton parts on corpuses

### ISSUE THREAD

**Issue by LudwigVonChesterfield** [miki151/keeperrl#1574]
Allow for moddable blacklist(and whitelist) support on automaton corpuses so many different creatures/mechanics can be born out of default automaton parts(per say, necromancer)

**Comment by miki151** [comment]
Do you mean multiple "types" of parts, for example automatons, undead, etc?

**Comment by LudwigVonChesterfield** [comment]
I was thinking either having a whitelist/blacklist for part ItemTypes like
whitelistParts = {
  {Simple PART_1}
}

or some flag that can be put on parts(but that would be much less moddable, so I'd rather prefer otpion 1)

**Comment by miki151** [comment]
You can do this now by specifying automatonType on a part and a list of types in automatonSlots in a creature.
