### ISSUE TITLE
Support NOT logic using "DoNothing" effect

### ISSUE THREAD

**Issue by SoftMonster** [miki151/keeperrl#1589]
Set it up so you can use FirstSuccessful to do a NOT operation.

Example:

FirstSuccessful {
  FilterLasting BLIND DoNothing
  Chain { Message "A red beam shoots from your eyes." Damage SPELL_DAMAGE SPELL }
}

So, the logic above is: If NOT Blind then Blast-Enemy-With-Eye-Beam

**Comment by SoftMonster** [comment]
AND logic currently looks like this:

FilterLasting BLIND FilterLasting SLOWED Message "You are blind and slowed."

**Comment by SoftMonster** [comment]
OR logic currently looks like this:

FirstSuccessful {
FilterLasting BLIND Message "You are blind or slowed."
FilterLasting SLOWED Message "You are blind or slowed."
Message "You are not blind or slowed."
}

**Comment by SoftMonster** [comment]
NOT BLIND OR SLOWED

FirstSuccessful {
FilterLasting BLIND DoNothing
FilterLasting SLOWED DoNothing
Message "You are not blind or slowed."
}

**Comment by SoftMonster** [comment]
(NOT BLIND) AND SLOWED

FirstSuccessful {
FilterLasting BLIND DoNothing
FilterLasting SLOWED "You are not blind, but are slowed."
}

**Comment by SoftMonster** [comment]
So to summarize, DoNothing might be kind of useful.

**Comment by miki151** [comment]
I've added CreaturePredicate which allows this kind of logic.

Ex: {Potion Filter And { LastingEffect BLIND Not LastingEffect SLOWED } Fire}

https://github.com/miki151/keeperrl/commit/5186da9187af2838ce5f1c486395c0b7e7f1d401
