### ISSUE TITLE
Protect adventures from being caught in an endless loop of being frozen

### ISSUE THREAD

**Issue by SoftMonster** [miki151/keeperrl#1614]
Player was complaining today on Discord that they were frozen endlessly and refrozen etc. while the turn timer ticked away.

Players frozen for 1000 turns should die or become cold resistant for a while. Or something else, but don't make them shut down the game using the operating system :)

**Comment by miki151** [comment]
Thanks, I've increased the ice cone spell timeout to 15 turns.
