### ISSUE TITLE
Increase the amount of gold needed to trigger bandits

### ISSUE THREAD

**Issue by SoftMonster** [miki151/keeperrl#1615]
Getting attacked by 4 lots of bandits for having 100 gold right at the start of the game is painful. Increasing the trigger limit to 400 gold would let the player dig out the first lot of gold before getting attacked.

There are some other alternatives, such as creating lots of other types of monsters that don't trigger or changing some more of the aggro bandits to non-aggro bandits.

Some new players do find this really hard and never get into the playing game. Myself, I often just don't build a treasure chest until I want to be attacked.

**Comment by miki151** [comment]
I increased the limit to 500 and changed is that there is a maximum of one aggro bandit/orc enemy per game. Thanks! Let me know if you get any other signals of unfairness.
