### ISSUE TITLE
Modding Dwarves produced tomb stone.

### ISSUE THREAD

**Issue by taldarus** [miki151/keeperrl#1740]
Not sure if it is a bug or intentional, but I can't get the game to properly display modded dwarves as a playable faction.

All I can get is a tomb stone.

Changed every single creatureId, viewId, etc multiple times and in multiple ways. Ended up completely rewriting the code, and I can only get a tomb stone.

Made a mini mod and updated my old mod from 29 ->  31, and they both work/display correctly. I haven't gone through the code to see if it is intentional or not.

**Comment by GameDungeon** [comment]
I think the faction not properly displaying is more an issue with your mod then the game

**Comment by taldarus** [comment]
I wrote, rewrote, and re-rewrote the file. To be clear.

I also then made a new mod, and restored another out of date mod to compare my methodology. The other two work, but the moment I switch to the dwarves, I end on a tomb stone icon for every dwarf. I was assuming it was meant as a memorial or something.

My methodology was something like:
"dwarf_warrior" 
"df_war"
"tal_df_war"
"taldwarf_war"

Were all checked and rechecked. I compared and cross referenced for typos. There are NO error messages. The mod loads perfectly fine, but displays a tomb stone. 

If it wasn't programed to do that intentionally, I believe that qualifies as a bug.

**Comment by GameDungeon** [comment]
Just because it loads fine does not mean there is not an error in the mod. I've been modding this game for a while now and I have never encountered this or seen someone else encounter this. Link the mod here, please.

**Comment by miki151** [comment]
A tombstone will be displayed if a tile sprite can't be found. Where in the game do you see the tombstone? There is too little information, best if you can upload your mod somewhere.

**Comment by taldarus** [comment]
I don't know if I have the final version of the dwarf mod files. Included are two sets of files: dumps_* (V3) and the Rewrites (V4).

I stopped working on it, when the rewrites didn't work either. 

I actually wanted to disconnect, but my son wanted to add a creature to his keeper experience. So I went through the process and warned him I wasn't sure it would work, because I thought I was doing something wrong.

His silly little monster worked. That's when I went through and updated my mods files to see if it works. And it does.

Note: An additional point of interest is that on the select keeper menu, I see a tomb stone. On map generator, I see the dwarf queen. In game play all Dwarves are stones again.

https://github.com/taldarus/dwarfmod

https://github.com/taldarus/Ringmod

As far as I can tell my methodology is identical, so I am really scratching my head. Before my son did his, I was assuming I was missing something. After both of ours works, I was wondering if you did something to rig it. Once I started writing this, I remembered the queen showed up on the map part. I can do a screen grab later, and I can also provide a verbose report if I knew how. Come to think of it, I have no idea how to do that on steam...

**Comment by GameDungeon** [comment]
Why do they say dump before them?

**Comment by GameDungeon** [comment]
OK I think I see the issue, none of the creatures brackets are closed. if you want further help please stop by the keeperRL Discord and ping me :)

code here: https://hastebin.com/ozamosiwiw.properties
This **Should** fix it.

**Comment by taldarus** [comment]
How did I get the bracket backwards? O.o

If that was on the computer I think it was, it should have been automatic. Oh well, set sail for fail!
