### ISSUE TITLE
Cardinal Area

### ISSUE THREAD

**Issue by GameDungeon** [miki151/keeperrl#1801]
Either add:

- Area 0 just gets the 4 cardinal directions
Or

- Add a circular version of Area that can do the same at radius 1

**Comment by G3Kappa** [comment]
Alternatively, provide a variant of `CustomArea` that doesn't rotate with the caster, to be used in furniture. This would make implementing `CardinalArea` in E++ trivial.

**Comment by miki151** [comment]
I've added a DistanceD predicate which gets you a circular area, so you can get cardinal neighbors by doing: Area 1 DistanceD 0 1 Effect.
