### ISSUE TITLE
Area iterators should return the state of the map before the current turn started

### ISSUE THREAD

**Issue by G3Kappa** [miki151/keeperrl#1806]
Area iterators should return the state of the map *before* the current turn started. Currently they don't, and while that's usually fine, it can cause subtle priority bugs wherein tiles to the bottom-right of the current tile are seen in their "old" state, while tiles to the top-left are seen in their "new" state.

This can be verified experimentally by creating a simple furniture type, which we'll call a *grounded wire*, and its powered counterpart, which we'll call a *live wire*.

A wire is placed in its grounded state, but when it's cardinally adjacent to a live wire (or to any arbitrary power source) it becomes live. Live wires will turn back into grounded wires on the next tick. Both of these mechanics are implemented with a custom tick type.

Now, for the purposes of determining the cardinal neighbors (since CustomArea rotates I can't use it), I'm using a temporary hack based on a binary counter and Area 1. Essentially, I'm just counting the odd-indexed neighbors and disregarding the rest, so a reproducible example will require some "library code".

But even if you ignore this part, the issue persists: electricity moves "slowly" backwards, and instantly forwards. That's because tiles to the bottom-right of the current tile will see it after it has updated, so if it becomes live, they will see it as live on the same tick that it became live, while tiles to the top-left will have to wait until the next tick in order to see this change.

Now I'm not really concerned about wires in particular, but about the concept of storing and working with information on the game map. If there was a reliable way to effectively "transfer" information at a constant speed across the map, you could build all sorts of interesting mods...

Some ideas that come to mind:

- Wires and electronics for remote control of traps, doors, and other installments; counters, memory, and other furniture that helps with information storage and processing without burdening E++
- Factorio-like assembly lines with belts that carry items around (might need some item-related stuff for this tho)
- Modular industries (such as furniture that needs to be adjacent to other furniture in order to work; this can be done already but this issue poses some roadblocks)
- Cellular automata (for cool special effects such as fire rings that expand outwards, or something along those lines)

**Comment by G3Kappa** [comment]
After reading the relevant code, I'm starting to think that this might not be straightforward to implement. I'm experimenting on a private fork with a predicate named `HasTicked` that could be used to at least know whether a tile has been updated or not.

**Comment by miki151** [comment]
I don't think this is doable as the game doesn't store any previous state. But if I understand your problem correctly, it can be solved by doing one pass that marks tiles for change, for example by placing some temporary furniture, and a second pass that does the change only on marked tiles. This way things should propagate at the same pace in all directions. Hit me up on discord if this is unclear or won't work for some reason.

**Comment by G3Kappa** [comment]
> 
> 
> I don't think this is doable as the game doesn't store any previous state. But if I understand your problem correctly, it can be solved by doing one pass that marks tiles for change, for example by placing some temporary furniture, and a second pass that does the change only on marked tiles. This way things should propagate at the same pace in all directions. Hit me up on discord if this is unclear or won't work for some reason.

Hi Miki, I didn't catch your response but I did some work along those lines and eventually got electricity working, albeit very slowly (I think it effectively "moved" at a rate of 1 tile every 4 ticks or so). I eventually shelved the idea for the time being, after delving a bit into the code and understanding that my proposed change wasn't as simple as I initially thought.

But I think that there's still room for thought, so I'll hit you up as soon as I come back to this.
