### ISSUE TITLE
Silent Steam Crash - Terminal of ./keeper output error ZLIB

### ISSUE THREAD

**Issue by Hawk-v3** [miki151/keeperrl#1829]
Hi!

As per above, I get a silent crash on launch with the error:
./keeper: ./libz.so.1: version `ZLIB_1.2.9' not found (required by /lib/x86_64-linux-gnu/libpng16.so.16)
My system is a Lubuntu install on default settings updated today. The system header is:
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

Checking here:
sudo apt show zlib1g
[sudo] password for hawk: 
Package: zlib1g
Version: 1:1.2.11.dfsg-2ubuntu1.2

I'm assuming something didn't get updated, could you please tell me if this is a problem with Keeper, Steam's install of it, or if my Lubuntu install has thrown a wobbly?

Thanks!

**Comment by Hawk-v3** [comment]
As a followup, I tried to compile your code as per instructions to try and find out if there was something I'm missing, but found that make fails, missing libtheora-dev from the requirements, and then fails out missing steamworks/steam_api and at that requirement, my googling also fails me to finish the compile.

Sorry I couldn't debug further.

**Comment by miki151** [comment]
Hi, it has been reported that you can fix this issue by removing libz.so.1 from the game's folder. I haven't figured out yet if that's a proper solution, please let me know if it works for you.

**Comment by Hawk-v3** [comment]
Hi, this has worked for me, the game starts and loads a map. I will report if any weirdness happens.

**Comment by Hawk-v3** [comment]
I have had no issues since doing this. Thank you.
