### ISSUE TITLE
UI too small

### ISSUE THREAD

**Issue by 0Karakurt0** [miki151/keeperrl#1851]
![image](https://user-images.githubusercontent.com/43828023/142487975-2c7c6aa3-a246-40e8-9669-9524e4b1a39c.png)
![image](https://user-images.githubusercontent.com/43828023/142488005-d1c387c5-650e-4746-9ab0-9a9028da8b30.png)
same on the opening animatic, but main menu is kind of ok - it can get into same quater-shape, but toggling fullscreen (using Window Manager hotkeys) helps.

Version 2020-11-16 73ae2 (got from torrent, didn't know that it was opensource. I'll try compiling/releases later)

OS: Arch Linux x86_64
Host: 80MJ Lenovo ideapad 100-15IBY
Kernel: 5.15.2-zen1-1-zen
Shell: zsh 5.8
Resolution: 1366x768
WM: i3
Terminal: alacritty
CPU: Intel Celeron N2840 (2) @ 2.582GHz
GPU: Intel Atom Processor Z36xxx/Z37xxx Series Graphics & Display
Memory: 1044MiB / 3819MiB

**Comment by miki151** [comment]
You've pirated my game and you're sending me bug reports?? This is an old bug, it has been fixed since. Buy the game and you'll get access to the newest versions.
