### ISSUE TITLE
When the minion works in workshop, Keeper attacks them

### ISSUE THREAD

**Issue by ivan-mogilko** [miki151/keeperrl#1862]
Playing Alpha 33 hotfix 11, during tutorial, I made a workshop and ordered a club. The goblin minion came to workshop and start working, and immediately the Keeper, who was nearby, attacked the goblin (the health was not reduced though). The attacks stopped right after the work was done.

Because working in workshop looks like the minion punching workshop stands, i wonder if the Keeper's AI considered that to be an attack on the dungeon?

**Comment by GameDungeon** [comment]
The keeper also was working at the workshop lol

**Comment by ivan-mogilko** [comment]
> The keeper also was working at the workshop lol

I could misunderstand this, but I clearly saw the red flashes on the goblin minion, and it looked like the Keeper was making moves towards goblin.

Only 1 item was ordered at workshop, how many units can work on 1 item together?

**Comment by GameDungeon** [comment]
> Only 1 item was ordered at workshop, how many units can work on 1 item together?
8 to be exact 🤷 
> Because working in workshop looks like the minion punching workshop stands, i wonder if the Keeper's AI considered that to be an attack on the dungeon?
Minions could not care less about what is happening to the dungeon, they only do stuff if they see an enemy or an alarm goes off

**Comment by ivan-mogilko** [comment]
I checked again, and can confirm: keeper is "attacking" goblin. It moves towards goblin and goblin flashes red. I may post a video if necessary.

**Comment by GameDungeon** [comment]
Is the goblin insane?

**Comment by GameDungeon** [comment]
Ohh wait. Its' the abuse minion animation. Got to wip some speed into minions.

**Comment by ivan-mogilko** [comment]
> Ohh wait. Its' the abuse minion animation. Got to whip some speed into minions.

Oh. Is it a new feature? The last version I played was Alpha 28, couple of years ago. Is there a way to turn this on/off to confirm it's the case?

**Comment by GameDungeon** [comment]
If you click on the keepers activity in the creature menu, there is a checkbox

**Comment by ivan-mogilko** [comment]
> If you click on the keepers activity in the creature menu, there is a checkbox

Alright, I confirm that was the case. Sorry for the false alarm :).
