### ISSUE TITLE
anything killed by bleeding mechanic is not registered

### ISSUE THREAD

**Issue by samuellsk** [miki151/keeperrl#1989]
if its status effect (like peasnt is bleeding) and he bleeds to death , kill is not registered (no combat xp  , no kill) , if its a tribe leader title will not be rewarded.
if Bleed is used (from effect_type.h) in a spell , the result is the same as above.
**if Bleed is used (from effect_type.h) by furniture (like building a trap) , combat xp and kill is rewarded to the builder of the furniture**
if Bleed is used (from effect_type.h) by furniture (for example to spawn furniture that would be killing using the effect) the result is that no kill / combat xp is rewarded

**Comment by miki151** [comment]
I think it's fixed now, please reopen if you still notice any issues.

**Comment by samuellsk** [comment]
> I think it's fixed now, please reopen if you still notice any issues.

Yes it does work as intended after last update.  THANK YOU>
