### ISSUE TITLE
linux : cannot build without steam support

### ISSUE THREAD

**Issue by tim-oleksii** [miki151/keeperrl#1990]
Hello,

I can't build on Linux without Steam support. `NO_STEAMWORKS` doesn't do a trick as there are references to `MySteamInput` in *.cpp files

**Comment by nega0** [comment]
894e69df is the last rev on the stable branch before the latest merge from master.

```console
$ git checkout 894e69df
```

**Comment by miki151** [comment]
Sorry, but it would take quite a bit of work to fix this, I recommend grabbing steam sdk and building with it.
