### ISSUE TITLE
add owner to the gas when placed by the effect

### ISSUE THREAD

**Issue by skorvaga** [miki151/keeperrl#1995]
just like furniture is placed and has owner where filter enemy can be used. i want the same for the gas.
as long as gas is active filters cannot be used now.

now gas belongs to "noone" and hence effect being applied based upon the filter enemy is not applied or applied to everyone.

**Comment by miki151** [comment]
The problem is that gas is a quantity and can mix, so tracking an owner would be error-prone. Is there any other thing you could (potentially) filter on?

**Comment by samuellsk** [comment]
> The problem is that gas is a quantity and can mix, so tracking an owner would be error-prone. Is there any other thing you could (potentially) filter on?

Yes i m filtering for something else , but i ll be rrworking it as whole and gas would be used just for the effect.
Can be closed.  Thank you.
