### ISSUE TITLE
Iron doors

### ISSUE THREAD

**Issue by miki151** [miki151/keeperrl#200]

**Comment by orangy** [comment]
I made a change to add Stone and Steel doors, working good. Except for the door locking. Adding second Furniture type for each type of door for locked state seems like a copy/paste overkill. 

I was thinking about adding a FurnitureModifier abstraction. It's something than can be attached/detached from the Furniture without adding too much items. It renders as an overlay. It gets its own ticks, etc. Fire could be an example of the same abstraction. What do you think?

**Comment by miki151** [comment]
Sorry for replying so late. You are right, I needed to remove the "locked door" furniture. I ended up just changing the door's movement permissions on click. The code actually got simpler...

Anyway, I added iron and steel doors.

https://github.com/miki151/keeperrl/commit/0cdc6b63c11f5e184e52364a569f932de800f978
https://github.com/miki151/keeperrl/commit/bbb2e29911f5fbc726833870614f4975c117c1ed
