### ISSUE TITLE
consider saving "hashed" sprites in retired keepers and removing mod needed requirement

### ISSUE THREAD

**Issue by samuellsk** [miki151/keeperrl#2015]
The idea is simple.

the config is already loaded during the creation of the game. The only thing that is missing are sprites. Since that could be some problem with "distribution" whatever... hash them during retirement and load them / unhash when keeper is used - maybe its not needed at all. I dunno.

And why ? Well this way you can load the whole keeper without having mod. Imagine the posibilities...

**Comment by miki151** [comment]
I considered it when adding modding, but it would be too complicated. I think the current solution works fine.
