### ISSUE TITLE
Consider of use "custom message" when using furniture with "UsageEffect"

### ISSUE THREAD

**Issue by samuellsk** [miki151/keeperrl#2020]
Now ingame "use"  is constructed with  "UsageEffect"  + "furniture name"  translating into  "eat from dining table" ingame.

"DINING_TABLE" inherit "JEWELLER"
{
  viewId = { "dining_table" }
  name = "dining table"
  usageFX = none
  diningFurniture = true
  usageType = UsageEffect "eat from" Filter Humanoid {
    CreatureMessage { "eat a steaming pig" "eats a steaming pig"}
    Lasting SATIATED
  }
}

Consider allowing us to create a custom "use" not including furniture name.

"UsageEffectCustom"  will not include furnitre name and ingame would be just what you wrote there

**Comment by miki151** [comment]
I unhardcoded to furniture name from the question, so you can just use UsageEffect to ask whatever you want.
