### ISSUE TITLE
Consider unhardcoding "Gold" from attack_trigger

### ISSUE THREAD

**Issue by samuellsk** [miki151/keeperrl#2030]
Would be useful, or less awkward to have for example elves getting attack based upon how much wood you have, or dwarfs how much adamantium, undead based villain how much corpses...  not everyone might be greedy for a gold :)

Please consider chanding "gold" into resourceid , where we can use any resource we want.

Thank you.

**Comment by miki151** [comment]
Done, good idea. I'll add usage of other resources later.
