### ISSUE TITLE
allow percentual damage against undead with effect

### ISSUE THREAD

**Issue by samuellsk** [miki151/keeperrl#2032]
Now doing "guaranteed" damage is done through bleeding

for example:
Bleed 0.25 "crushed by claw"

But this will not goona do anydmg against undead, since they are immune to bleeding mechanics. This way many custom spells do fail agains them.

Fixed damage function will gonna do fixed stat dmg eg , 80 damage, but that can be fatal to many creatures and to some higher xp would not gonna do much...

Please consider doing a copy of the Bleed effect that could be used as universal percentual dmg against minions unless invulnerable.

**Comment by miki151** [comment]
Try this:
Filter Not HasAnyHealth Chance [Percentage] {
    CreatureMessage "lose a limb" "loses a limb"
   ChooseRandom {
        InjureBodyPart LEG
        InjureBodyPart ARM
        ...
    }

This will do almost the same thing as the regular attack code. You can choose to include BACK or TORSO depending on whether you want the attack to be lethal.

Please reopen if something doesn't work.
