### ISSUE TITLE
Hands are not feet

### ISSUE THREAD

**Issue by KA101** [miki151/keeperrl#2033]
https://github.com/miki151/keeperrl/blob/0b9f053197396bdff80d0b141c9c7017cc3f23ac/data_free/game_config/creatures.txt#L4365

Since Adoxie's limbs are all copied from the left foot, that means that the **hands** also ask you why you thought a **foot** could talk.

Respectfully suggest adding new chat lines for the hands, asking why you thought a hand could talk.

**Comment by miki151** [comment]
Fixed, thanks.

**Comment by samuellsk** [comment]
you sure ? 

"ADOXIE_HAND_RIGHT" inherit "ADOXIE_LEFT_HAND"
  {
    viewId = { "adoxie_hand_right" }
    name = {
      name = "Adoxie's Right Hand"
      pluralName = "Hands"
      fullTitle = true
    }
    chatReactionFriendly = "\"nothing, why did you think a foot could talk?\""
    chatReactionHostile = "\"nothing, why did you think a foot could talk?\""
  }

thats from github creatures.txt

**Comment by KA101** [comment]
I'm afraid Rarasek's right.  Looks like you just copied the line into the hands, without changing "foot" to "hand".
