### ISSUE TITLE
Steeds don't use their abilities

### ISSUE THREAD

**Issue by muturgan** [miki151/keeperrl#2040]
Saddled Ki-rin (probably not only Ki-rin) uses magic missiles but don't heal itself. And don't use other buffs. After unmounting Ki-rin heals itself first of all. It would be great if the steeds used all their abilities regardless of the rider.

**Comment by KA101** [comment]
Bit late (apologies) but checking: was the ki-rin a slave, or had you converted it?  Slave Steeds don't fight for their masters, they need to be converted first.

**Comment by muturgan** [comment]
Oh really? Interesting. I didn't do anything special. So ki-rin was still a slave. To be honest, I haven't seen any mechanics to convert sledges. Will check it. Thank you!
