### ISSUE TITLE
Cure blindness spell does not cure blindness

### ISSUE THREAD

**Issue by JanSimek** [miki151/keeperrl#2062]
Example: I have a vampire warrior who is blind and has an injured head. When I try to cure him with the Cure blindness spell by a goblin priest nothing happens.

I would post my current save, but I don't know where the saves are located on linux.

**Comment by KA101** [comment]
Injured/destroyed body parts require regrowth (in vanilla KeeperRL, via a potion of regrow-limbs, vampire-bite limb regrowth, or a gnomish automaton being repaired by a player-faction gnome).  Until then, whatever the lost body-part did is Gone.  Without a head, the vampire will remain blind and unable to bite (or wear a helmet; I think it'd block amulets too).

Sorry for the delayed response, though I'm pretty certain it's not a Bug.

**Comment by JanSimek** [comment]
Thank you for the explanation. I am closing this issue but in my opinion, it should be made a bit clearer how to do that ingame.
