### ISSUE TITLE
Change libSFML to one more standar as libSDL for example

### ISSUE THREAD

**Issue by mdtrooper** [miki151/keeperrl#301]
Hi.

I have been trying to install the dev libs for SFML in my machine, but there are not some this dev libs in easy package. My machines is:

```
$ lsb_release --all
No LSB modules are available.
Distributor ID: LinuxMint
Description:    Linux Mint 14 Nadia
Release:    14
Codename:   nadia
```

I know this change is some dificult, sorry, but I want to help in the code.

Regards.

**Comment by miki151** [comment]
Finally done :)
