### ISSUE TITLE
Make keeperrl system-wide installable

### ISSUE THREAD

**Issue by akien-mga** [miki151/keeperrl#376]
KeeperRL currently loads its data from the runtime directory, and if I'm not mistaken it also write its logs and saves in the runtime directory. This cause two issues for Linux packaging:

* The game binary and the data have to be in the same directory, which is against policy on most Linux distributions. Usually game data would go to ${prefix}/share/games/keeperrl (at least on Mageia, Fedora or Debian) or to ${prefix}/share/keeperrl. When packaging the ${prefix} would be set to /usr, while it would be /usr/local as default (for user installations after compiling "by hand".
Same goes for the game binary that would go to ${prefix}/games (or ${prefix}/bin on some distros).
=> For now this can be worked around by putting everything together in ${prefix}/share/games/keeperrl and creating a wrapper script in ${prefix}/games to launch the game from the correct directory.

* ${prefix}/share/games/keeperrl is a read-only directory for the user, so it's not possible to write the config, logs and saves files in there. They should be put respectively in ~/.config/keeperrl and ~/.local/share/keeperrl.
This can't be worked around since it causes a segmentation fault upon start the game:
```
[akien@cauldron keeperrl]$ pwd
/usr/share/games/keeperrl
[akien@cauldron keeperrl]$ ./keeper 
terminate called after throwing an instance of 'std::string'
Abandon
```

**Comment by miki151** [comment]
Ok, check this commit:
https://github.com/miki151/keeperrl/commit/d36bbcc10b5b05f1210a38f261e84f762c748890

The static data is read from (in order of precedence):
* program flag, for example. keeper --data_dir=/usr/local/share/keeperrl
* a make file flag DATA_DIR
If neither are set then it reads from current dir.

The save files and settings are read from (in order of precedence):
* program flag, for example. keeper --user_dir=~/.local/share/keeperrl
* XDG_DATA_HOME env variable
* make file flag USER_DIR
If neither are set then it reads from current dir.

If the directory doesn't exist, it will be created.

If you are packaging for a distro, then should probably initialize USER_DIR to something in case XDG_DATA_HOME is not set.

**Comment by miki151** [comment]
Btw, I'm releasing alpha13 in a few days, so this should make it to the stable branch soon.

**Comment by Bertram25** [comment]
Heya @miki151 :)

Ok, I've seen nothing obviously wrong in the patch.
I'll test the stable alpha13 in a few days and tell you if anything goes wrong.

Best regards, and all the best!

**Comment by akien-mga** [comment]
Hi @miki151, thanks for your patch.
It seems to work fine, but I'm having one issue with the USER_DIR flag: XDG_DATA_HOME is indeed unset on Mageia so I need to set the USER_DIR manually, but I can't see how to make it point to $HOME/.local/share/keeperrl.

Even if I escape the $ in $HOME, it eventually always ends up being /home/akien instead of staying a variable. There might be a way to workaround that, but maybe you could also hardcore $HOME/.local/share/keeperrl when XDG_DATA_HOME is undefined?

**Comment by miki151** [comment]
Feel free to branch it off yourself, the relevant code is in main.cpp

**Comment by akien-mga** [comment]
Done in #568

**Comment by miki151** [comment]
Closing for now, let me know of any other trouble.

**Comment by Mailaender** [comment]
Have parts of https://github.com/miki151/keeperrl/pull/568 been integrated already or has it died off? The pull request is still open, but greyed out because of merge conflicts. I guess that means I also can't generate a patch from it anymore.

**Comment by miki151** [comment]
Sorry, I was just too busy with other stuff.

**Comment by Mailaender** [comment]
I suggest you reopen the issue then.

**Comment by miki151** [comment]
If you need something done then just do it. I didn't release the source
code for the game so I can do extra work for others, especially if they act
like it's my job, and even send me reminders.

Just take the source code as is. You can send me an email and ask very
kindly for a feature. I'm very busy developing the game and actually trying
to make a living from it.

**Comment by Mailaender** [comment]
Calm down. We are volunteer community maintainers for Linux distributions packaging your game in our free time. No one gets a piece of your cake. If you don't appreciate that. Fine. We will blacklist you as bad upstream and move along. Good bye.

**Comment by akien-mga** [comment]
> If you need something done then just do it.

That's exactly what #568 is about, a kind contribution from the open source community to improve a feature. Now, you are perfectly free not to take it into account, downstream packagers can probably make their own patches based on it.

**Comment by miki151** [comment]
I already wrote that I prefer not to merge it. I think it's pretty easy to
do your packages off a branch. I know that it broke at some point, but in
general I don't touch that part of the code a lot, so maintaining it isn't
going to be too hard.

**Comment by akien-mga** [comment]
> I'm very busy developing the game and actually trying to make a living from it.

As a side note, I'm very supportive of your effort to make a commercially-viable open source game. I often take you and Tales of Maj'Eyal as examples of (relatively, I don't know the figures) successful open source indie games, and I'm really glad that you decided to keep the code open source even when going commercial.

And I could also understand if you're not seeing kindly the fact that downstream maintainers want to package the ascii version of your game for free when you're trying to sell it. I see it differently though, as people who play the ascii version downloaded through their distribution's package manager will hear about KeeperRL, and might be interested in buying the commercial version, either to get tiles or just to support development.

**Comment by akien-mga** [comment]
> I already wrote that I prefer not to merge it.

Well, as I said, everything is inside as #ifdef __linux__, so I don't see how it would break other platforms. But you know the code better than me :)

> I think it's pretty easy to do your packages off a branch.

Ok.

**Comment by Mailaender** [comment]
> And I could also understand if you're not seeing kindly the fact that downstream maintainers want to package the ascii version of your game for free when you're trying to sell it. I see it differently though, as people who play the ascii version downloaded through their distribution's package manager will hear about KeeperRL, and might be interested in buying the commercial version, either to get tiles or just to support development.

It would be easy to integrate a message (in the game or packaging scripts) that tells the player where to buy and place the graphical assets to support development like most Open Source game clones do it.

**Comment by miki151** [comment]
I'm perfectly fine with people playing the ascii version for free and that you guys package it. And there is that kind of message in the game.

**Comment by hasufell** [comment]
this is pretty short-sighted... having your own game packaged in distributions will greatly increase the number of potential customers and make it more widely known

gentoo will not touch it in this stage, because cooperativeness is very important for us since we don't like keeping tons of patches downstream
