### ISSUE TITLE
repeatable crasher bug

### ISSUE THREAD

**Issue by coledot** [miki151/keeperrl#587]
Please see the below save file (which is not actually a .jpg, but is just renamed for Github) from alpha13. If you load it and perform the following actions, it reliably triggers a crash (SIGABRT on Yosemite):
1. Control the level 24 Orc. (hard to miss, he is the first squad)
2. Attempt to remove one of his two rings of poison.
3. *kerpow*

![hipolon_velgartor](https://cloud.githubusercontent.com/assets/3317498/6407591/2f316818-bdf8-11e4-9d9a-a4d42695b8b0.jpg)

**Comment by miki151** [comment]
Fixed. Thanks for reporting!
