### ISSUE TITLE
Segfault when digging out of map

### ISSUE THREAD

**Issue by mklinik** [miki151/keeperrl#605]
There is a segfault when you mark tiles outside the map area for digging.

How to reproduce:

1. Scrool to a border of the map
2. Start marking tiles to dig inside the map
3. Drag the mouse to the area outside the map
Result: The program segfaults.

I'm using:
c25ee86bda6ea1fdc0aacc2a717e4dc3b467e986
ASCII mode

**Comment by miki151** [comment]
That's a really fresh bug, I just fixed it. Thank you!
