### ISSUE TITLE
Add linux libraries

### ISSUE THREAD

**Issue by miki151** [miki151/keeperrl#673]
./keeper: error while loading shared libraries: libnettle.so.4: cannot open shared object file: No such file or directory

**Comment by hickop** [comment]
Will it gets fixed soon ? Can't play KeeperRL because of that (alpha14 & steam on Archlinux).
Tell me if you need more info debugging that.
Thanks.

**Comment by miki151** [comment]
Sorry, I'll add them next week when I get back home. Have you tried
installing libnettle?

On Sun, May 10, 2015 at 10:17 AM, Mathieu Quinette <notifications@github.com

**Comment by hickop** [comment]
I have nettle 3.1.1 and lib32-nettle 3.1.1 installed. In my /usr/lib I have: libnettle.so.6.1, libnettle.so.6 (symlink to 6.1) and libnettle.so (symlink to 6.1).
Symlinking libnettle.so.4 to my 6.1 gets me this now:
```bash
./keeper: /usr/lib/libldap_r-2.4.so.2: no version information available (required by ./libcurl.so.4)
./keeper: /usr/lib/liblber-2.4.so.2: no version information available (required by ./libcurl.so.4)
./keeper: /usr/lib/libssl.so.1.0.0: no version information available (required by ./libcurl.so.4)
./keeper: /usr/lib/libssl.so.1.0.0: no version information available (required by ./libcurl.so.4)
./keeper: /usr/lib/libcrypto.so.1.0.0: no version information available (required by ./libcurl.so.4)
./keeper: symbol lookup error: ./libgnutls-deb0.so.28: undefined symbol: nettle_camellia_crypt
```

**Comment by miki151** [comment]
Ok, so your version is too recent and incompatible. I'll add libnettle.4 to
steam, sorry for the inconvenience.

**Comment by hickop** [comment]
Made it working with some symlinking black magic.

```bash
$ mv libgnutls-deb0.so.28 libgnutls-deb0.so.28.old
$ ln -s /usr/lib/libgnutls.so.30 libgnutls-deb0.so.28
$ mv librtmp.so.1 librtmp.so.1.old
$ ln -s /usr/lib/librtmp.so.1 librtmp.so.1
```

Temporary fix until you provide all libs that KeeperRL require.
