### ISSUE TITLE
openSUSE:Factory — /bin/sh: -c: line 0: syntax error near unexpected token `(' 

### ISSUE THREAD

**Issue by DAP-DarkneSS** [miki151/keeperrl#683]
[  918s] g++ -Wall -std=c++0x -Wno-sign-compare -Wno-unused-variable -Wfatal-errors -Wno-shift-count-overflow -Wno-tautological-constant-out-of-range-compare -g -I. -I./extern -o keeper obj/time_queue.o obj/level.o obj/model.o obj/square.o obj/util.o obj/monster.o obj/square_factory.o obj/view.o obj/creature.o obj/item_factory.o obj/item.o obj/inventory.o obj/debug.o obj/player.o obj/window_view.o obj/field_of_view.o obj/view_object.o obj/creature_factory.o obj/shortest_path.o obj/effect.o obj/equipment.o obj/level_maker.o obj/monster_ai.o obj/attack.o obj/tribe.o obj/name_generator.o obj/event.o obj/location.o obj/skill.o obj/fire.o obj/ranged_weapon.o obj/map_layout.o obj/trigger.o obj/map_memory.o obj/view_index.o obj/pantheon.o obj/enemy_check.o obj/collective.o obj/player_control.o obj/task.o obj/controller.o obj/village_control.o obj/poison_gas.o obj/minion_equipment.o obj/statistics.o obj/options.o obj/renderer.o obj/tile.o obj/map_gui.o obj/gui_elem.o obj/item_attributes.o obj/creature_attributes.o obj/serialization.o obj/unique_entity.o obj/entity_set.o obj/gender.o obj/main.o obj/gzstream.o obj/singleton.o obj/technology.o obj/encyclopedia.o obj/input_queue.o obj/minimap_gui.o obj/music.o obj/test.o obj/sectors.o obj/vision.o obj/animation.o obj/clock.o obj/square_type.o obj/creature_action.o obj/collective_control.o obj/renderable.o obj/bucket_map.o obj/task_map.o obj/movement_type.o obj/collective_builder.o obj/player_message.o obj/minion_task_map.o obj/gui_builder.o obj/known_tiles.o obj/collective_teams.o obj/progress_meter.o obj/entity_name.o obj/collective_config.o obj/spell.o obj/spell_map.o obj/spectator.o obj/visibility_map.o obj/model_builder.o obj/file_sharing.o obj/stack_printer.o obj/highscores.o obj/main_loop.o -L/usr/lib/x86_64-linux-gnu -lsfml-audio -lsfml-graphics -lsfml-window -lsfml-system -lboost_serialization -lboost_program_options -lboost_filesystem -lboost_system -lz -lpthread -lcurl (RPATH) -static-libstdc++
[  918s] /bin/sh: -c: line 0: syntax error near unexpected token `('
[  918s] /bin/sh: -c: line 0: `g++ -Wall -std=c++0x -Wno-sign-compare -Wno-unused-variable -Wfatal-errors -Wno-shift-count-overflow -Wno-tautological-constant-out-of-range-compare -g -I. -I./extern -o keeper obj/time_queue.o obj/level.o obj/model.o obj/square.o obj/util.o obj/monster.o obj/square_factory.o obj/view.o obj/creature.o obj/item_factory.o obj/item.o obj/inventory.o obj/debug.o obj/player.o obj/window_view.o obj/field_of_view.o obj/view_object.o obj/creature_factory.o obj/shortest_path.o obj/effect.o obj/equipment.o obj/level_maker.o obj/monster_ai.o obj/attack.o obj/tribe.o obj/name_generator.o obj/event.o obj/location.o obj/skill.o obj/fire.o obj/ranged_weapon.o obj/map_layout.o obj/trigger.o obj/map_memory.o obj/view_index.o obj/pantheon.o obj/enemy_check.o obj/collective.o obj/player_control.o obj/task.o obj/controller.o obj/village_control.o obj/poison_gas.o obj/minion_equipment.o obj/statistics.o obj/options.o obj/renderer.o obj/tile.o obj/map_gui.o obj/gui_elem.o obj/item_attributes.o obj/creature_attributes.o obj/serialization.o obj/unique_entity.o obj/entity_set.o obj/gender.o obj/main.o obj/gzstream.o obj/singleton.o obj/technology.o obj/encyclopedia.o obj/input_queue.o obj/minimap_gui.o obj/music.o obj/test.o obj/sectors.o obj/vision.o obj/animation.o obj/clock.o obj/square_type.o obj/creature_action.o obj/collective_control.o obj/renderable.o obj/bucket_map.o obj/task_map.o obj/movement_type.o obj/collective_builder.o obj/player_message.o obj/minion_task_map.o obj/gui_builder.o obj/known_tiles.o obj/collective_teams.o obj/progress_meter.o obj/entity_name.o obj/collective_config.o obj/spell.o obj/spell_map.o obj/spectator.o obj/visibility_map.o obj/model_builder.o obj/file_sharing.o obj/stack_printer.o obj/highscores.o obj/main_loop.o -L/usr/lib/x86_64-linux-gnu -lsfml-audio -lsfml-graphics -lsfml-window -lsfml-system -lboost_serialization -lboost_program_options -lboost_filesystem -lboost_system -lz -lpthread -lcurl (RPATH) -static-libstdc++'
[  918s] Makefile:109: recipe for target 'keeper' failed
[  918s] make: *** [keeper] Error 1

**Comment by miki151** [comment]
Sorry, I don't know what's the problem.

**Comment by DAP-DarkneSS** [comment]
> Closed #683.

Cool.
