### ISSUE TITLE
Magic schools

### ISSUE THREAD

**Issue by miki151** [miki151/keeperrl#694]
Attack
- fire sphere
- word of power
- meteor shower
- force bolt
- stun ray

Healing
- healing
- cure poison
- regenerate body part

Self-enhancing
- speed self
- strength bonus
- dexterity bonus
- invisibility
- magic shield

Escape
- deception
- escape / teleport
- portal

Summoning
- summon insects
- summon spirits

**Comment by GameDoungen** [comment]
Added
