### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [miki151/keeperrl#744]
I would like to point out that identifiers like "[`_ANIMATION_H`](https://github.com/miki151/keeperrl/blob/5add237175331ad03a484d814f914f9de49a1306/animation.h#L1)" and "[`_CREATURE_H`](https://github.com/miki151/keeperrl/blob/240a1a7787a7968ce1cf0cd43d302395f1322306/creature.h#L16)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by miki151** [comment]
Sure, is it causing you any problems?

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by miki151** [comment]
It doesn't bother me at all, frankly, I'll get a compile error if there is
a collision of names.
