### ISSUE TITLE
non-virtual destructor warning build failure

### ISSUE THREAD

**Issue by dvolk** [miki151/keeperrl#745]
In file included from model.cpp:1:
    In file included from /home/dv/src/games/keeperrl/stdafx.h:53:
    In file included from /home/dv/src/games/keeperrl/./extern/portable_iarchive.hpp:89:
    In file included from /home/dv/src/lib/boost_1_56_0/boost/archive/basic_binary_iprimitive.hpp:56:
    In file included from /home/dv/src/lib/boost_1_56_0/boost/serialization/array.hpp:23:
    In file included from /home/dv/src/lib/boost_1_56_0/boost/serialization/nvp.hpp:29:
    In file included from /home/dv/src/lib/boost_1_56_0/boost/serialization/split_member.hpp:23:
    /home/dv/src/lib/boost_1_56_0/boost/serialization/access.hpp:125:9: fatal error: delete called on 'Collective' that has virtual functions but non-virtual
          destructor [-Wdelete-non-virtual-dtor]
            delete const_cast<T *>(t);

Removing -Werror allows it to build successfully

Ubuntu clang version 3.5.2-0ubuntu1 (tags/RELEASE_352/final) (based on LLVM 3.5.2)

**Comment by miki151** [comment]
Fixed, thanks.
