### ISSUE TITLE
Doors tool tip doesn't change

### ISSUE THREAD

**Issue by Hunteil** [miki151/keeperrl#754]
Using Alpha 17 ASCII, Windows 7, 64
Keeper Mode

When you click a door to lock them. It changes color to blue. But the tooltip still says to click to lock.

**Comment by Hunteil** [comment]
Sometimes when I press to activate a door for locking. I found that if I turn on dig, then right click to cancel the operation, then click the door. It'll work. (Pausing time flow doesn't matter it seems.)

**Comment by miki151** [comment]
Fixed
