### ISSUE TITLE
Error Uploading file at completion

### ISSUE THREAD

**Issue by Hunteil** [miki151/keeperrl#756]
Using Alpha 17 (Full Version), Windows 7, 64
Keeper Mode

Hello, finally beat the game and when I used retire game. I received this error.

![error retire](https://cloud.githubusercontent.com/assets/8192771/11694327/77adbfd2-9e77-11e5-8afb-d030263e5e3a.png)

Is this normal???

I made my map with some item secrets for adventurers to have a chance at beating the Dungeon. I wanted it to have a chance for someone to win. :-)

**Comment by miki151** [comment]
Can you tell me how large is the file? It has a "ret" extension.

**Comment by Hunteil** [comment]
9792 KB.

**Comment by Hunteil** [comment]
Error triggered again with a new game. The file size was 10,243 KB.

I updated the original image to help reflect the notes.

**Comment by miki151** [comment]
Limit was increased to 20mb.
