### ISSUE TITLE
Pigs stuck in walls

### ISSUE THREAD

**Issue by Hunteil** [miki151/keeperrl#758]
Area was a Pigsty,
Deleted and moved room to another area. Pigs remained and never moved and no minions ever visited to eat them. Used Fill Tunnel command and was able to trap them in the walls.

Multiple options for fix:
1. Pigs move to new/existing pigsty rooms.
2. Setting minions to target pigs in general, instead of pigsty room. This way they eat any pig. (idk what the code says for this.)
3. If a creature is in a wall, they are automatically pushed to the closest open space.

![error pig in wall](https://cloud.githubusercontent.com/assets/8192771/11694540/a0d84d2c-9e78-11e5-8f3d-209ba8ce6566.jpg)

**Comment by miki151** [comment]
Pigs shouldn't stay in deleted pigsties

**Comment by miki151** [comment]
This was fixed, I think.
