### ISSUE TITLE
Creating Teams missing 3rd drag & drop option

### ISSUE THREAD

**Issue by Hunteil** [miki151/keeperrl#759]
Simple, currently the team creation works right now. But the 3rd way to create teams is missing. This post is to create that feature.

The image explains what works and what doesn't.
![teams](https://cloud.githubusercontent.com/assets/8192771/11708505/ef2a2364-9edd-11e5-9884-6e23c003132a.jpg)

**Comment by miki151** [comment]
So what should it do? Add all minions from that group to the team?

**Comment by Hunteil** [comment]
Yup. And if you want, you can give a warning message. But it should be fine. They'll understand when it happens on larger groups.

**Comment by miki151** [comment]
Also done. Thanks :)
