### ISSUE TITLE
Doppelganger Absorb will delete equipment

### ISSUE THREAD

**Issue by Hunteil** [miki151/keeperrl#762]
After I noticed the Doppelganger absorbing one of my best minions. I realized the Equipment the dead creature had was nowhere to be found. The dead creature had a Gold or Rare or Legendary level weapon which is now gone. All the armor and gear is gone too.

The Doppelganger can equip items. Maybe it should gain the items when they absorb.

**Comment by miki151** [comment]
The normal behaviour is to drop the equipment, I confirmed in the source code and in practice. It's possibly a bug, or maybe he got absorbed while over water?
