### ISSUE TITLE
Minimap needs a border so you can see it in dark areas

### ISSUE THREAD

**Issue by Hunteil** [miki151/keeperrl#768]
Currently, the minimap is whatever color the mapped area is. There was a few complaints that people couldn't get back to their area easily in the beginning. To get back to their area, they can easily use the minimap, but without a border, it's black in black areas, it's hard to see. This can be easily fixed with a simple colored border and maybe a instruction tip.

![minimap](https://cloud.githubusercontent.com/assets/8192771/11795588/9233ce02-a285-11e5-9b72-070dd7efd639.jpg)

Mainly a thing to help newer players that don't know about the minimap features yet.

**Comment by miki151** [comment]
Fixed.
