### ISSUE TITLE
Doors can be dug out to stand alone without purpose

### ISSUE THREAD

**Issue by Hunteil** [miki151/keeperrl#769]
Maybe make them fall apart if there's no wall next to them. Or allow double doors.
Attach picture, I cannot place doors next to this door. It just sits there useless.

I recall someone asking for double doors.
![door_stands_alone](https://cloud.githubusercontent.com/assets/8192771/11795970/b019ef12-a287-11e5-8c22-c6097e6fe2f1.jpg)

**Comment by miki151** [comment]
I guess they could fall apart.

**Comment by miki151** [comment]
This was fixed some time ago.
