### ISSUE TITLE
[crash] "load game"

### ISSUE THREAD

**Issue by skhaen** [miki151/keeperrl#804]
When i try to load a "Recovered games" or a "Keeper games", the game crash with the following popup:

```
FATALdebug.cpp:27 Assertion at /usr/local/include/boost/optional/optional.hpp:992
```
### CONFIG:
- Debian 8 (with systemd) - 64 bits
- KeeperRL alpha 19 (2016-07-26 7a18-dirty) from itch.io 
- keeper_lin64.sh

**Comment by miki151** [comment]
Thanks. Can you paste the contents of stacktrace.out please?

**Comment by skhaen** [comment]
tail -f stracktrace.out:

```
tail: stacktrace.out : fichier tronqué
FATALdebug.cpp:27 Assertion at /usr/local/include/boost/optional/optional.hpp:992
Caught SIGSEGV: Segmentation Fault
Current time 1469552006, running time 70
_Z23posix_print_stack_tracev à ??:?
_Z20posix_signal_handleriP9siginfo_tPv à ??:?
?? ??:0
_ZN5DebugD1Ev à ??:?
_ZN5boost16assertion_failedEPKcS1_S1_l à ??:?
_ZN8MainLoop8loadGameESs à ??:?
_ZN8MainLoop12loadPreviousEv à ??:?
_ZN8MainLoop14playGameChoiceEv à ??:?
_ZN8MainLoop5startEb à ??:?
_ZZL10keeperMainRKN5boost15program_options13variables_mapEENKUlvE0_clEv à main.cpp:?
_ZL10keeperMainRKN5boost15program_options13variables_mapE à main.cpp:?
main à ??:?
?? ??:0
_start à ??:?
```

**Comment by miki151** [comment]
So you can save a game but loading crashes every time? Someone has reported
this error on Linux already. Is you Debian setup non-standard?

**Comment by skhaen** [comment]
i don't know if the save process is really effective, i bought the game 3 hours ago. 

My Debian is a Debian 8 (Jessie) standard.

and i don't have a /usr/local/include/boost/optional/optional.hpp file.

**Comment by skhaen** [comment]
How i can help you to fix this? Do you need more debug?

**Comment by miki151** [comment]
I think it's a bug in boost, and I'm using a pretty old version, so
tomorrow I'll send you a build with a newer version and we'll see if it
helps. We'll go from there. Sorry for the inconvenience.

**Comment by skhaen** [comment]
Yay! \o/
Thanks you!

**Comment by skhaen** [comment]
Oh, by the way, I use cinnamon and not gnome !
https://packages.debian.org/jessie/cinnamon

**Comment by miki151** [comment]
Can you confirm that starting a game, saving and then loading it causes a
crash?

I'll send you another build in a moment and we'll see if the same thing
happens.

**Comment by skhaen** [comment]
starting a game -->  saving (autosave or manual) --> loading --> crash

**Comment by miki151** [comment]
Ok, unpack this binary and put it in the game's directory. Try the same
thing (remember to load the new game that you just saved).

http://blkrs.com/~michal/keeper.gz

**Comment by skhaen** [comment]
* unpack the binary in  `lin64` (replace `keeper` file)
* create a new game --> save
* load --> same bug, the game crash :/

**Comment by miki151** [comment]
I see, I'll try a newer version of boost then.

Btw, have you tried the 32-bit version of keeper? It should work on most
64-bit systems.

**Comment by skhaen** [comment]
I just tried the 32 bits, i can't running it without [libjpeg8](https://packages.debian.org/sid/libjpeg8), available only on Debian Wheezy and Debian Sid

```./keeper: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory
```

The libjpeg version is not the same in the 64 bits and the 32 bits version ? 

```
laptop:~/jeux/keeperRL dpkg -l|grep jpeg
ii  libjpeg62-turbo:amd64                 1:1.3.1-12
ii  libjpeg62-turbo:i386                  1:1.3.1-12
ii  libjpeg62-turbo-dev:i386              1:1.3.1-12
ii  libmjpegutils-2.1-0                   1:2.1.0+debian-3
ii  libopenjpeg2:amd64                    1.3+dfsg-4.8
ii  libopenjpeg5:amd64                    1:1.5.2-3
ii  libopenjpeg5:i386                     1:1.5.2-3
```

**Comment by miki151** [comment]
You are right, you would need to install multilib, not worth the trouble.

I'll get back to you later today or tomorrow.

**Comment by skhaen** [comment]
Hi,
Do you have some news about a newer version of boost?

**Comment by miki151** [comment]
Yes, sorry for the delay. Unzip and put these files in the keeper
directory: http://blkrs.com/~michal/boost_1_61.zip

Let me know if it works, I always run into some compatibility problems when
upgrading libraries.

**Comment by skhaen** [comment]
don't run :/

1/ unzip the archive in `lin64/`

```
tech:~/data/jeux/keeperRL ls lin64/
-rw-r--r-- 1 skhaen skhaen       20 juil. 26 18:51 installId.txt
-rwxr-xr-x 1 skhaen skhaen 25073440 juil. 31 18:31 keeper
-rwxrwxr-x 1 skhaen skhaen 25646664 juil. 26 15:31 keeper_old
-rwxr-xr-x 1 skhaen skhaen   121168 juil. 26 15:31 libboost_filesystem.so.1.57.0
-rwxr-xr-x 1 skhaen skhaen   119912 juil. 31 18:24 libboost_filesystem.so.1.61.0
-rwxr-xr-x 1 skhaen skhaen   574256 juil. 26 15:31 libboost_program_options.so.1.57.0
-rwxr-xr-x 1 skhaen skhaen   597848 juil. 31 18:24 libboost_program_options.so.1.61.0
-rwxr-xr-x 1 skhaen skhaen   567096 juil. 26 15:31 libboost_serialization.so.1.57.0
-rwxr-xr-x 1 skhaen skhaen   425080 juil. 31 18:24 libboost_serialization.so.1.61.0
-rwxr-xr-x 1 skhaen skhaen    20464 juil. 26 15:31 libboost_system.so.1.57.0
-rwxr-xr-x 1 skhaen skhaen    19608 juil. 31 18:24 libboost_system.so.1.61.0
-rwxr-xr-x 1 skhaen skhaen   306696 juil. 31 18:24 libboost_wserialization.so.1.61.0
[...]
```
2/ run the game

```
tech:~/data/jeux/keeperRL ./keeper_lin64.sh
./keeper: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./libboost_serialization.so.1.61.0)
./keeper: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./libboost_program_options.so.1.61.0)
./keeper: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./libboost_filesystem.so.1.61.0)
./keeper: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./libboost_system.so.1.61.0)
```

 what can i do? need more debug?

**Comment by miki151** [comment]
Ok, just a moment, I need to recompile it with an older compiler.

**Comment by miki151** [comment]
Ok, please repeat the previous procedure.

**Comment by skhaen** [comment]
I can play and save. And the game crash when i try to load a new saving party.

![selection_019](https://cloud.githubusercontent.com/assets/977699/17278728/07b646c6-5764-11e6-84fb-10ded7e6f194.png)

stracktrace : 

```
FATALdebug.cpp:27 Assertion at /home/michal/Downloads/boost_1_61_0/boost/optional/optional.hpp:868
Caught SIGSEGV: Segmentation Fault
Current time 1469992276, running time 13
_Z23posix_print_stack_tracev à ??:?
_Z20posix_signal_handleriP9siginfo_tPv à ??:?
?? ??:0
_ZN5DebugD1Ev à ??:?
_ZN5boost16assertion_failedEPKcS1_S1_l à ??:?
_ZN8MainLoop8loadGameESs à ??:?
_ZN8MainLoop12loadPreviousEv à ??:?
_ZN8MainLoop14playGameChoiceEv à ??:?
_ZN8MainLoop5startEb à ??:?
_ZZL10keeperMainRKN5boost15program_options13variables_mapEENKUlvE0_clEv à main.cpp:?
_ZL10keeperMainRKN5boost15program_options13variables_mapE à main.cpp:?
main à ??:?
?? ??:0
_start à ??:?
```

Mmh, `/home/michal/Downloads/boost_1_61_0/boost` ? Did you forget a PATH somewhere (my home is /home/skhaen)? :)

**Comment by miki151** [comment]
That's the same error as you had before, isn't it? I don't have any more
ideas at the moment, but I'll think about it.

The /home/michal/... is the path where I built boost on my machine.

**Comment by skhaen** [comment]
Not exactly no, with the last release of the game (alpha 19) without any patchs, i have this:

![selection_020](https://cloud.githubusercontent.com/assets/977699/17278800/3121cec0-5766-11e6-8633-5621a3c185da.png)

stacktrace:

```
FATALdebug.cpp:27 Assertion at /usr/local/include/boost/optional/optional.hpp:992
Caught SIGSEGV: Segmentation Fault
Current time 1469993353, running time 225
_Z23posix_print_stack_tracev à ??:?
_Z20posix_signal_handleriP9siginfo_tPv à ??:?
?? ??:0
_ZN5DebugD1Ev à ??:?
_ZN5boost16assertion_failedEPKcS1_S1_l à ??:?
_ZN8MainLoop8loadGameESs à ??:?
_ZN8MainLoop12loadPreviousEv à ??:?
_ZN8MainLoop14playGameChoiceEv à ??:?
_ZN8MainLoop5startEb à ??:?
_ZZL10keeperMainRKN5boost15program_options13variables_mapEENKUlvE0_clEv à main.cpp:?
_ZL10keeperMainRKN5boost15program_options13variables_mapE à main.cpp:?
main à ??:?
?? ??:0
_start à ??:?
```

without your PATH in it.

I will wait for a patch, i want to play, thanks for your time :)

**Comment by skhaen** [comment]
I think you have a hardlink somewhere in your code who target your home, it can't run anywhere else.

**Comment by miki151** [comment]
No, it's completely normal to have paths from the build machine in the
debug symbols.

**Comment by tamas821** [comment]
Hi Everyone,
I am experiencing the same issue with alpha21 on Linux Mint 18.1 Cinnamon 64-bit.
Game runs, saving goes through, but loading causes crash.
Content of stacktrace.out is:
> FATAL debug.cpp:27 Assertion at /usr/local/include/boost/optional/optional.hpp:992
>Caught SIGSEGV: Segmentation Fault
>Current time 1488192724, running time 12
>std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, >std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, >std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >const&) at ??:?
>std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, >std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, >std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >const&) at ??:?
>?? ??:0
>virtual thunk to >boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_option>s::validation_error> >::rethrow() const at ??:?
>virtual thunk to >boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_option>s::validation_error> >::rethrow() const at ??:?
>boost::archive::detail::archive_serializer_map<boost::archive::text_iarchive>::erase(boost::archive::deta>il::basic_serializer const*) at ??:?
>boost::archive::detail::archive_serializer_map<boost::archive::text_iarchive>::erase(boost::archive::deta>il::basic_serializer const*) at ??:?
>boost::archive::detail::archive_serializer_map<boost::archive::text_iarchive>::erase(boost::archive::deta>il::basic_serializer const*) at ??:?
>boost::archive::detail::archive_serializer_map<boost::archive::text_iarchive>::erase(boost::archive::deta>il::basic_serializer const*) at ??:?
>boost::archive::detail::archive_serializer_map<boost::archive::text_iarchive>::erase(boost::archive::deta>il::basic_serializer const*) at ??:?
>std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, >std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, >std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >const&) at ??:?
>std::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, >std::char_traits<char>, std::allocator<char> >(std::basic_string<char, std::char_traits<char>, >std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >const&) at ??:?
>?? ??:0
>?? ??:0
>?? ??:0

**Comment by miki151** [comment]
Are you running the game on Steam or from the standalone download?

Do you have boost installed on your system? My suspicion is that the game
loads the system boost libraries instead of ones that come with it. Any
chance that you could temporarily remove boost from your system and try to
see if it helped?

Thanks.

**Comment by tamas821** [comment]
I am running the standalone version.
Based on the short google search I did, yes, I believe boost is installed on my system.
I am happy to help if I can, however, I am not very confident about which packages to remove.
Would removing these do the trick?

>/usr/lib/x86_64-linux-gnu/libboost_system.so.1.58.0
>/usr/lib/x86_64-linux-gnu/libboost_iostreams.so.1.58.0
>/usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.58.0
>/usr/lib/x86_64-linux-gnu/libboost_date_time.so.1.58.0

**Comment by miki151** [comment]
Sorry, it turned out that there was a bug in the game in the standalone
version that involved loading games. Please wait an hour or two for an
update to see if it fixed your issue.

**Comment by miki151** [comment]
It should be fixed now. Let me know if there are any other problems.
