### ISSUE TITLE
Severe performance degradation with minion management screen open

### ISSUE THREAD

**Issue by stuartdb** [miki151/keeperrl#811]
Debian Stretch x64
Steam Build 2016-08-02 c54f-dirty

Chugging along normally:
![Before openeing minion management](http://i.imgur.com/gseM8TD.png)

After opening minion management (~3 FPS)
![After openeing minion management](http://i.imgur.com/qnOjmBj.png)

[Link to save file](https://ufile.io/82422)

**Comment by stuartdb** [comment]
Possibly linked to how much equipment or consumables are either equipped or owned? 

[Here is an example of a save ](https://ufile.io/56226)file from an earlier keep before I had grasped the concept of equipment and equipping. There is no performance hit when opening the minion management screen.

**Comment by miki151** [comment]
Fixed in the master branch with a simple optimization. There is still some lag, as you guessed correctly, due to large number of items, but fixing it completely will require bigger changes.

Thanks for reporting.
