### ISSUE TITLE
[crash] OSX - load game

### ISSUE THREAD

**Issue by jakofranko** [miki151/keeperrl#813]
I just downloaded the alpha19 free version and the game crashes every time when I try to load a game.

```
Running the game from /Users/jfranklin/Games/keeperRL_alpha19_free
libpng warning: iCCP: known incorrect sRGB profile
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Assertion failed: (this->is_initialized()), function get, file /usr/include/boost/optional/optional.hpp, line 1005.
```

At first I thought it was an issue with boost not being found in `/usr/include/boost` but I symlinked my homebrew version the include dir of boost to that location and the `option.hpp` file is definitely located in that path... any ideas?

**Comment by jakofranko** [comment]
Might be a dupe of #804

**Comment by miki151** [comment]
I'm 99% sure that this is fixed, please re-open if not.
