### ISSUE TITLE
Potion of body regeneration

### ISSUE THREAD

**Issue by miki151** [miki151/keeperrl#906]
Recovers one lost limb

**Comment by nzero** [comment]
please!

**Comment by Evillee03** [comment]
Would have to be costly, or make it a special event, the blood of a priest, 10 killed prisoners take their souls and infuse them into said potion. Or destroy one civilization, use their life force to make the potion. Anything like that just make it feel worthless.

**Comment by miki151** [comment]
Made it an artifact held by the lizard lord.
