### ISSUE TITLE
Autosaving loop

### ISSUE THREAD

**Issue by heuripedes** [miki151/keeperrl#929]
Twice today I've ran into an autosave loop. In both times it happened while I tried to open something. 

1st time: running alpha21hotfix1 under wine. I was controlling a werewolf and tried to open a chest.
2st time: running alpha21hotfix2 under wine. I was controlling an ogre and tried to open a coffin.

In both cases as soon as I pressed [Enter] to open the object the game started ignoring my input. Buttons on the (minion) sidebar get highlighted when the mouse goes over but they don't trigger any actions. Shortcuts don't work.

I am running the free/ASCII version of the game under wine on linux. I am unable to run the native linux version due to incompatible library versions (I have libsasl2.so.3 instead of libsasl2.so.2).

I attached the save file of the last game. When I load it the game just continues the autosave loop.
[ENYGMATA_ValdeaNN4O.zip](https://github.com/miki151/keeperrl/files/819889/ENYGMATA_ValdeaNN4O.zip)

**Comment by heuripedes** [comment]
Somebody reported the same bug @ the forum: http://keeperrl.com/forums/topic/alpha-21-autosaving-loop/

**Comment by miki151** [comment]
Hey, thanks a lot for the report.

The save file is corrupted, so you probably closed the game while it was
saving. (I realize it might be hard to get a proper save while the game is
saving in a loop).

I've never stumbled on this bug, so it's probably not very common. If it
happens again, can you try to remember any additional circumstances?

In any case, I'll keep an eye for it.

I'll try to fix the library incompatibility. What distro were you on?

**Comment by heuripedes** [comment]
This one seems to work. In the "room" there are five chests, the one hidden under an orc at the top right triggers the issue more often. Sometimes it's one of the ones at the bottom right.

[ENYGMATA_FionaranthzkCQ.zip](https://github.com/miki151/keeperrl/files/829114/ENYGMATA_FionaranthzkCQ.zip)

I'm using Arch Linux. Both 32 and 64 bit builds can't find `libsasl2.so.2` or `libgssapi.so.3`.

I tried compiling it but I get a bunch of errors related to `boost::optional`:
[build errors.txt](https://github.com/miki151/keeperrl/files/829158/make.txt)

Some info:

    uname -a: Linux whiterice 4.9.11-1-ARCH #1 SMP PREEMPT Sun Feb 19 13:45:52 UTC 2017 x86_64 GNU/Linux
    clang: clang version 3.9.1 (tags/RELEASE_391/final)
    boost: 1.63

**Comment by miki151** [comment]
I found the bug, thank you. It was a heap corruption, and it didn't always
fail, but the bug surfaced when I turned on the memory sanitizer (clang
flag -fsanitize=address). I hope I can roll out a fix to this quickly.

For compiling yourself, I recommend installing boost 1.57. Newer versions
cause save compatibility issues, and also these compile problems.

**Comment by heuripedes** [comment]
Hotfix3 fixed it, thanks.
Just one minor issue: the Github repo isn't up to date with the latest changes.
